export const esmaNames = [
    { id: 1, arabic: "اَللّٰهُ", name: "Allah", meaning: "Eşi benzeri olmayan, bütün noksan sıfatlardan münezzeh tek ilah, Her şeyin gerçek mabudu." },
    { id: 2, arabic: "اَلرَّحْمٰنُ", name: "Er-Rahmân", meaning: "Dünyada bütün mahlûkata merhamet eden, şefkat gösteren, ihsan eden." },
    { id: 3, arabic: "اَلرَّحِيمُ", name: "Er-Rahîm", meaning: "Ahirette, müminlere sonsuz ikram, lütuf ve ihsanda bulunan." },
    { id: 4, arabic: "اَلْمَلِكُ", name: "El-Melik", meaning: "Mülkün, kâinatın sahibi, mülk ve saltanatı devamlı olan." },
    { id: 5, arabic: "اَلْقُدُّوسُ", name: "El-Kuddûs", meaning: "Her noksanlıktan uzak ve her türlü takdîse lâyık olan." },
    { id: 6, arabic: "اَلسَّلاَمُ", name: "Es-Selâm", meaning: "Her türlü tehlikelerden selamete erdiren." },
    { id: 7, arabic: "اَلْمُؤْمِنُ", name: "El-Mü’min", meaning: "Güven veren, emin kılan, koruyan." },
    { id: 8, arabic: "اَلْمُهَيْمِنُ", name: "El-Müheymin", meaning: "Her şeyi görüp gözeten." },
    { id: 9, arabic: "اَلْعَزِيزُ", name: "El-Azîz", meaning: "İzzet sahibi, her şeye galip olan." },
    { id: 10, arabic: "اَلْجَبَّارُ", name: "El-Cebbâr", meaning: "Azamet ve kudret sahibi. Dilediğini yapan ve yaptıran." },
    { id: 11, arabic: "اَلْمُتَكَبِّرُ", name: "El-Mütekebbir", meaning: "Büyüklükte eşi, benzeri olmayan." },
    { id: 12, arabic: "اَلْخَالِقُ", name: "El-Hâlık", meaning: "Yaratan, yoktan var eden." },
    { id: 13, arabic: "اَلْبَارِئُ", name: "El-Bâri", meaning: "Her şeyi kusursuz ve uyumlu yaratan." },
    { id: 14, arabic: "اَلْمُصَوِّرُ", name: "El-Musavvir", meaning: "Varlıklara şekil veren." },
    { id: 15, arabic: "اَلْغَفَّارُ", name: "El-Gaffâr", meaning: "Günahları örten ve çok mağfiret eden." },
    { id: 16, arabic: "اَلْقَهَّارُ", name: "El-Kahhâr", meaning: "Her şeye, her istediğini yapacak surette galip ve hakim olan." },
    { id: 17, arabic: "اَلْوَهَّابُ", name: "El-Vehhâb", meaning: "Karşılıksız hibeler veren, çok fazla ihsan eden." },
    { id: 18, arabic: "اَلرَّزَّاقُ", name: "Er-Rezzâk", meaning: "Bütün mahlûkatın rızkını veren ve ihtiyacını karşılayan." },
    { id: 19, arabic: "اَلْفَتَّاحُ", name: "El-Fettâh", meaning: "Her türlü müşkülleri açan ve kolaylaştıran, darlıktan kurtaran." },
    { id: 20, arabic: "اَلْعَلِيمُ", name: "El-Alîm", meaning: "Her şeyi en ince noktasına kadar bilen, ilmi ebedi ve ezeli olan." },
    { id: 21, arabic: "اَلْقَابِضُ", name: "El-Kâbıd", meaning: "Dilediğine darlık veren, sıkan, daraltan." },
    { id: 22, arabic: "اَلْبَاسِطُ", name: "El-Bâsıt", meaning: "Dilediğine bolluk veren, açan, genişleten." },
    { id: 23, arabic: "اَلْخَافِضُ", name: "El-Hâfıd", meaning: "Dereceleri alçaltan." },
    { id: 24, arabic: "اَلرَّافِعُ", name: "Er-Râfi", meaning: "Şeref verip yükselten." },
    { id: 25, arabic: "اَلْمُعِزُّ", name: "El-Muizz", meaning: "Dilediğini aziz eden, izzet veren." },
    { id: 26, arabic: "اَلْمُذِلُّ", name: "El-Müzill", meaning: "Dilediğini zillete düşüren." },
    { id: 27, arabic: "اَلسَّمِيعُ", name: "Es-Semi", meaning: "Her şeyi en iyi işiten." },
    { id: 28, arabic: "اَلْبَصِيرُ", name: "El-Basîr", meaning: "Gizli açık, her şeyi en iyi gören." },
    { id: 29, arabic: "اَلْحَكَمُ", name: "El-Hakem", meaning: "Mutlak hakim, hakkı batıldan ayıran. Hikmetle hükmeden." },
    { id: 30, arabic: "اَلْعَدْلُ", name: "El-Adl", meaning: "Mutlak adil, çok adaletli." },
    { id: 31, arabic: "اَللَّطِيفُ", name: "El-Latîf", meaning: "Lütuf ve ihsan sahibi olan. Bütün incelikleri bilen." },
    { id: 32, arabic: "اَلْخَبِيرُ", name: "El-Habîr", meaning: "Olmuş olacak her şeyden haberdar." },
    { id: 33, arabic: "اَلْحَلِيمُ", name: "El-Halîm", meaning: "Cezada, acele etmeyen, yumuşak davranan." },
    { id: 34, arabic: "اَلْعَظِيمُ", name: "El-Azîm", meaning: "Büyüklükte benzeri yok. Pek yüce." },
    { id: 35, arabic: "اَلْغَفُورُ", name: "El-Gafûr", meaning: "Affı, mağfireti bol." },
    { id: 36, arabic: "اَلشَّكُورُ", name: "Eş-Şekûr", meaning: "Az amele, çok sevap veren." },
    { id: 37, arabic: "اَلْعَلِيُّ", name: "El-Aliyy", meaning: "Yüceler yücesi, çok yüce." },
    { id: 38, arabic: "اَلْكَبِيرُ", name: "El-Kebîr", meaning: "Büyüklükte benzeri yok, pek büyük." },
    { id: 39, arabic: "اَلْحَفِيظُ", name: "El-Hafîz", meaning: "Her şeyi koruyucu olan." },
    { id: 40, arabic: "اَلْمُقِيتُ", name: "El-Mukît", meaning: "Her yaratılmışın rızkını, gıdasını veren, tayin eden." },
    { id: 41, arabic: "اَلْحَسِيبُ", name: "El-Hasîb", meaning: "Kulların hesabını en iyi gören." },
    { id: 42, arabic: "اَلْجَلِيلُ", name: "El-Celîl", meaning: "Celal ve azamet sahibi olan." },
    { id: 43, arabic: "اَلْكَرِيمُ", name: "El-Kerîm", meaning: "Keremi, lütfu ve ihsanı bol, karşılıksız veren, çok ikram eden." },
    { id: 44, arabic: "اَلرَّقِيبُ", name: "Er-Rakîb", meaning: "Her varlığı, her işi her an görüp, gözeten, kontrolü altında tutan." },
    { id: 45, arabic: "اَلْمُجِيبُ", name: "El-Mücîb", meaning: "Duaları, istekleri kabul eden." },
    { id: 46, arabic: "اَلْوَاسِعُ", name: "El-Vâsi", meaning: "Rahmet, kudret ve ilmi ile her şeyi ihata eden." },
    { id: 47, arabic: "اَلْحَكِيمُ", name: "El-Hakîm", meaning: "Her işi hikmetli, her şeyi hikmetle yaratan." },
    { id: 48, arabic: "اَلْوَدُودُ", name: "El-Vedûd", meaning: "Kullarını en çok seven, sevilmeye en layık olan." },
    { id: 49, arabic: "اَلْمَجِيدُ", name: "El-Mecîd", meaning: "Her türlü övgüye layık bulunan." },
    { id: 50, arabic: "اَلْبَاعِثُ", name: "El-Bâis", meaning: "Ölüleri dirilten." },
    { id: 51, arabic: "اeشَّهِيدُ", name: "Eş-Şehîd", meaning: "Her zaman her yerde hazır ve nazır olan." },
    { id: 52, arabic: "اَلْحَقُّ", name: "El-Hakk", meaning: "Varlığı hiç değişmeden duran. Var olan, hakkı ortaya çıkaran." },
    { id: 53, arabic: "اَلْوَكِيلُ", name: "El-Vekîl", meaning: "Kendisine tevekkül edenlerin işlerini en iyi neticeye ulaştıran." },
    { id: 54, arabic: "اَلْقَوِيُّ", name: "El-Kaviyy", meaning: "Kudreti en üstün ve hiç azalmaz." },
    { id: 55, arabic: "اَلْمَتِينُ", name: "El-Metîn", meaning: "Kuvvet ve kudret kaynağı, pek güçlü." },
    { id: 56, arabic: "اَلوَلِيُّ", name: "El-Veliyy", meaning: "İnananların dostu, onları seven ve yardım eden." },
    { id: 57, arabic: "اَلْحَمِيدُ", name: "El-Hamîd", meaning: "Her türlü hamd ve senaya layık olan." },
    { id: 58, arabic: "اَلْمُحْص۪ي", name: "El-Muhsî", meaning: "Yarattığı ve yaratacağı bütün varlıkların sayısını bilen." },
    { id: 59, arabic: "اَلْمُبْدِئُ", name: "El-Mübdi", meaning: "Maddesiz, örneksiz yaratan." },
    { id: 60, arabic: "اَلْمُعِيدُ", name: "El-Muîd", meaning: "Yarattıklarını yok edip, sonra tekrar diriltecek olan." },
    { id: 61, arabic: "اَلْمُحْي۪ي", name: "El-Muhyî", meaning: "İhya eden, dirilten, can veren." },
    { id: 62, arabic: "اَلْمُمِيتُ", name: "El-Mümît", meaning: "Her canlıya ölümü tattıran." },
    { id: 63, arabic: "اَلْحَيُّ", name: "El-Hayy", meaning: "Ezeli ve ebedi hayat sahibi." },
    { id: 64, arabic: "اَلْقَيُّومُ", name: "El-Kayyûm", meaning: "Varlıkları diri tutan, zatı ile kaim olan." },
    { id: 65, arabic: "اَلْوَاجِدُ", name: "El-Vâcid", meaning: "Kendisinden hiçbir şey gizli kalmayan, istediğini, istediği vakit bulan." },
    { id: 66, arabic: "اَلْمَاجِدُ", name: "El-Mâcid", meaning: "Kadri ve şanı büyük, keremi, ihsanı bol olan." },
    { id: 67, arabic: "اَلْوَاحِدُ", name: "El-Vâhid", meaning: "Zat, sıfat ve fiillerinde benzeri ve ortağı olmayan, tek olan." },
    { id: 68, arabic: "اeصَّمَدُ", name: "Es-Samed", meaning: "Hiçbir şeye ihtiyacı olmayan, herkesin muhtaç olduğu." },
    { id: 69, arabic: "اَلْقَادِرُ", name: "El-Kâdir", meaning: "Dilediğini dilediği gibi yaratmaya muktedir olan." },
    { id: 70, arabic: "اَلْمُقْتَدِرُ", name: "El-Muktedir", meaning: "Dilediği gibi tasarruf eden, her şeyi kolayca yaratan kudret sahibi." },
    { id: 71, arabic: "اَلْمُقَدِّمُ", name: "El-Mukaddim", meaning: "Dilediğini, öne alan, yükselten." },
    { id: 72, arabic: "اَلْمُؤَخِّرُ", name: "El-Muahhir", meaning: "Dilediğini sona alan, erteleyen, alçaltan." },
    { id: 73, arabic: "اَلْاَوَّلُ", name: "El-Evvel", meaning: "Ezeli olan, varlığının başlangıcı olmayan." },
    { id: 74, arabic: "اَلْاٰخِرُ", name: "El-Âhir", meaning: "Ebedi olan, varlığının sonu olmayan." },
    { id: 75, arabic: "اَلظَّاهِرُ", name: "Ez-Zâhir", meaning: "Varlığı sayısız delillerle açık olan." },
    { id: 76, arabic: "اَلْبَاطِنُ", name: "El-Bâtın", meaning: "Akılların idrak edemeyeceği, yüceliği gizli olan." },
    { id: 77, arabic: "اَلْوَالِي", name: "El-Vâlİ", meaning: "Bütün kâinatı idare eden." },
    { id: 78, arabic: "اَلْمُتَعَالِي", name: "El-Müteâlî", meaning: "Son derece yüce olan." },
    { id: 79, arabic: "اَلْبَرُّ", name: "El-Berr", meaning: "İyilik ve ihsanı bol, iyilik yapan." },
    { id: 80, arabic: "اَلتَّوَّابُ", name: "Et-Tevvâb", meaning: "Tövbeleri kabul edip, günahları bağışlayan." },
    { id: 81, arabic: "اَلْمُنْتَقِمُ", name: "El-Müntekim", meaning: "Asilerin, zalimlerin cezasını veren." },
    { id: 82, arabic: "اَلْعَفُوُّ", name: "El-Afüvv", meaning: "Affeden, mağfiret eden." },
    { id: 83, arabic: "اَلرَّؤُفُ", name: "Er-Raûf", meaning: "Çok lütufkâr, çok esirgeyen." },
    { id: 84, arabic: "مَالِكُ الْمُلْكِ", name: "Mâlik-ül Mülk", meaning: "Mülkün, her varlığın sahibi." },
    { id: 85, arabic: "ذُوالْجَلَالِ وَالْاِكْرَامِ", name: "Zül-Celâli vel-İkrâm", meaning: "Celal, büyüklük ve ikram sahibi." },
    { id: 86, arabic: "اَلْمُقْسِطُ", name: "El-Muksıt", meaning: "Her işi birbirine uygun yapan." },
    { id: 87, arabic: "اَلْجَامِعُ", name: "El-Câmi", meaning: "Mahşerde her mahlûkatı bir araya toplayan." },
    { id: 88, arabic: "اَلْغَنِيُّ", name: "El-Ganiyy", meaning: "Her türlü zenginlik sahibi, ihtiyacı olmayan." },
    { id: 89, arabic: "اَلْمُغْنِي", name: "El-Muğnî", meaning: "Müstağni kılan. ihtiyaç gideren, zengin eden." },
    { id: 90, arabic: "اَلْمَانِعُ", name: "El-Mâni", meaning: "Bir şeyin meydana gelmesine izin vermeyen, engelleyen." },
    { id: 91, arabic: "اَضَّارُّ", name: "Ed-Dârr", meaning: "Elem, zarar verenleri yaratan." },
    { id: 92, arabic: "اَلنَّافِعُ", name: "En-Nâfi", meaning: "Fayda veren şeyleri yaratan." },
    { id: 93, arabic: "اَلنُّورُ", name: "En-Nûr", meaning: "Alemleri nurlandıran, dilediğine nur veren." },
    { id: 94, arabic: "اَلْهَادِي", name: "El-Hâdî", meaning: "Hidayet veren." },
    { id: 95, arabic: "اَلْبَدِيعُ", name: "El-Bedî", meaning: "Eşi ve benzeri olmayan güzellikler yaratan." },
    { id: 96, arabic: "اَلْبَاقِي", name: "El-Bâkî", meaning: "Varlığının sonu olmayan, ebedi olan." },
    { id: 97, arabic: "اَلْوَارِثُ", name: "El-Vâris", meaning: "Her şeyin asıl sahibi olan." },
    { id: 98, arabic: "اَلرَّشِيدُ", name: "Er-Reşîd", meaning: "İrşada muhtaç olmayan, doğru yolu gösteren." },
    { id: 99, arabic: "اَصَّبُورُ", name: "Es-Sabûr", meaning: "Ceza vermede acele etmeyen." }
];
