[
  { "id": 1, "metin": "Ameller (başka değil) ancak niyetlere göredir; herkesin niyeti ne ise eline geçecek odur.", "kaynak": "Buhârî, Bedü'l-vahy, 1" },
  { "id": 2, "metin": "Kolaylaştırınız, güçleştirmeyiniz; müjdeleyiniz, nefret ettirmeyiniz.", "kaynak": "Buhârî, İlim, 11" },
  { "id": 3, "metin": "Müslüman, dilinden ve elinden diğer Müslümanların emin olduğu kimsedir.", "kaynak": "Buhârî, Îmân, 4" },
  { "id": 4, "metin": "Allah’a ve ahiret gününe iman eden kimse ya hayır söylesin veya sussun.", "kaynak": "Buhârî, Edeb, 31" },
  { "id": 5, "metin": "Temizlik imanın yarısıdır.", "kaynak": "Müslim, Tahâret, 1" },
  { "id": 6, "metin": "Sizden biriniz, kendisi için istediğini mümin kardeşi için de istemedikçe (tam) iman etmiş olmaz.", "kaynak": "Buhârî, Îmân, 7" },
  { "id": 7, "metin": "Güçlü kimse, güreşte hasmını yenen pehlivan değil, öfkelendiği zaman nefsine hakim olan kimsedir.", "kaynak": "Buhârî, Edeb, 76" },
  { "id": 8, "metin": "Sizin en hayırlınız, ahlakı en güzel olanınızdır.", "kaynak": "Buhârî, Edeb, 38" },
  { "id": 9, "metin": "İnsanlara merhamet etmeyene Allah da merhamet etmez.", "kaynak": "Buhârî, Edeb, 18" },
  { "id": 10, "metin": "Haya (utanma duygusu) imandandır.", "kaynak": "Buhârî, Îmân, 16" },
  { "id": 11, "metin": "Dua, ibadetin özüdür.", "kaynak": "Tirmizî, Deavât, 1" },
  { "id": 12, "metin": "Veren el, alan elden üstündür.", "kaynak": "Buhârî, Zekât, 18" },
  { "id": 13, "metin": "Zulümden sakınınız. Çünkü zulüm, kıyamet gününde zifiri karanlık olacaktır.", "kaynak": "Müslim, Birr, 56" },
  { "id": 14, "metin": "Rızkının çoğalmasını ve ömrünün uzamasını isteyen kimse, akrabasını gözetip kollasın.", "kaynak": "Buhârî, Edeb, 12" },
  { "id": 15, "metin": "Cennetin anahtarı namazdır, namazın anahtarı ise abdesttir.", "kaynak": "Tirmizî, Tahâret, 1" },
  { "id": 16, "metin": "Doğruluktan ayrılmayınız. Doğruluk iyiliğe, iyilik de cennete götürür.", "kaynak": "Buhârî, Edeb, 69" },
  { "id": 17, "metin": "Gıybet, kardeşini hoşlanmadığı bir şeyle anmandır.", "kaynak": "Müslim, Birr, 70" },
  { "id": 18, "metin": "Günahından (samimiyetle) tövbe eden kimse, hiç günah işlememiş gibidir.", "kaynak": "İbn Mâce, Zühd, 30" },
  { "id": 19, "metin": "Hiç kimseye sabırdan daha hayırlı ve daha geniş bir nimet verilmemiştir.", "kaynak": "Buhârî, Zekât, 50" },
  { "id": 20, "metin": "Sizin en hayırlınız, Kuran'ı öğrenen ve öğretendir.", "kaynak": "Buhârî, Fedâilü'l-Kur'ân, 21" },
  { "id": 21, "metin": "İman etmedikçe cennete giremezsiniz, birbirinizi sevmedikçe de (tam) iman etmiş olmazsınız.", "kaynak": "Müslim, Îmân, 93" },
  { "id": 22, "metin": "Kardeşinin yüzüne tebessüm etmen senin için sadakadır.", "kaynak": "Tirmizî, Birr, 36" },
  { "id": 23, "metin": "Hediyeleşiniz, zira hediyeleşmek kalpteki kin ve nefreti giderir.", "kaynak": "Tirmizî, Velâ, 6" },
  { "id": 24, "metin": "İstişare eden pişman olmaz.", "kaynak": "Heysemî, Mecmeu’z-Zevâid, 2/280" },
  { "id": 25, "metin": "Hayra vesile olan, hayrı yapan gibidir.", "kaynak": "Tirmizî, İlim, 14" },
  { "id": 26, "metin": "Rabbin rızası anne babanın rızasında, Rabbin öfkesi anne babanın öfkesindedir.", "kaynak": "Tirmizî, Birr, 3" },
  { "id": 27, "metin": "Münafığın alameti üçtür: Konuştuğunda yalan söyler, söz verdiğinde sözünde durmaz, emanete hıyanet eder.", "kaynak": "Buhârî, Îmân, 24" },
  { "id": 28, "metin": "Kim Allah için alçakgönüllü davranırsa, Allah onu yüceltir.", "kaynak": "Müslim, Birr, 69" },
  { "id": 29, "metin": "Gerçek zenginlik mal çokluğu değil, gönül tokluğudur.", "kaynak": "Buhârî, Rikâk, 15" },
  { "id": 30, "metin": "Biriniz yemek yediği zaman sağ eliyle yesin, içtiği zaman da sağ eliyle içsin.", "kaynak": "Müslim, Eşribe, 105" },
  { "id": 31, "metin": "Müminin durumu ne hoştur! Her hali kendisi için hayırlıdır.", "kaynak": "Müslim, Zühd, 64" },
  { "id": 32, "metin": "Hiçbir kimse, elinin emeğinden daha hayırlı bir lokma yememiştir.", "kaynak": "Buhârî, Büyû, 15" },
  { "id": 33, "metin": "Ben ve yetimi kollayıp gözetleyen kimse, cennette (iki parmak gibi) yan yanayız.", "kaynak": "Buhârî, Talâk, 25" },
  { "id": 34, "metin": "Hasetten sakınınız. Çünkü ateşin odunu yiyip bitirdiği gibi haset de iyilikleri yer bitirir.", "kaynak": "Ebû Dâvûd, Edeb, 44" },
  { "id": 35, "metin": "Dünya, müminin zindanı, kafirin cennetidir.", "kaynak": "Müslim, Zühd, 1" },
  { "id": 36, "metin": "Bizi aldatan bizden değildir.", "kaynak": "Müslim, Îmân, 164" },
  { "id": 37, "metin": "İlim öğrenmek, her Müslümana farzdır.", "kaynak": "İbn Mâce, Mukaddime, 17" },
  { "id": 38, "metin": "Allah'a ve ahiret gününe iman eden kimse misafirine ikram etsin.", "kaynak": "Buhârî, Edeb, 31" },
  { "id": 39, "metin": "İnsanlara teşekkür etmeyen, Allah’a da şükretmez.", "kaynak": "Tirmizî, Birr, 35" },
  { "id": 40, "metin": "Sabah namazının iki rekat (sünnet)i, dünyadan ve dünyadaki her şeyden daha hayırlıdır.", "kaynak": "Müslim, Müsâfirîn, 96" },
  { "id": 41, "metin": "Mümin müminin aynasıdır.", "kaynak": "Ebû Dâvûd, Edeb, 49" },
  { "id": 42, "metin": "Laf getirip götüren (kovuculuk yapan) kimse cennete giremez.", "kaynak": "Buhârî, Edeb, 50" },
  { "id": 43, "metin": "İnsanlardan öyleleri vardır ki hayrın anahtarı, şerrin kilididirler.", "kaynak": "İbn Mâce, Mukaddime, 19" },
  { "id": 44, "metin": "Cemaatle kılınan namaz, tek başına kılınan namazdan yirmi yedi derece daha faziletlidir.", "kaynak": "Buhârî, Ezân, 30" },
  { "id": 45, "metin": "Hastayı ziyaret edin, aç olanı doyurun, esiri kurtarın.", "kaynak": "Buhârî, Cihâd, 171" },
  { "id": 46, "metin": "Sizden kim bir kötülük görürse onu eliyle düzeltsin; gücü yetmezse diliyle; ona da gücü yetmezse kalbiyle buğzetsin.", "kaynak": "Müslim, Îmân, 78" },
  { "id": 47, "metin": "Kabul edileceğine kesinlikle inanarak Allah’a dua edin.", "kaynak": "Tirmizî, Deavât, 65" },
  { "id": 48, "metin": "Nerede olursan ol, Allah’tan kork (takvalı ol).", "kaynak": "Tirmizî, Birr, 55" },
  { "id": 49, "metin": "Mümin bir delikten iki defa ısırılmaz (aynı hatayı iki kez yapmaz).", "kaynak": "Buhârî, Edeb, 83" },
  { "id": 50, "metin": "Bir müslümanın diktiği ağaçtan veya ektiği ekinden yedikleri şeyler, o müslüman için sadakadır.", "kaynak": "Buhârî, Edeb, 27" },
  { "id": 51, "metin": "Yarım hurma ile de olsa (sadaka vererek) kendinizi ateşten koruyun.", "kaynak": "Buhârî, Edeb, 34" },
  { "id": 52, "metin": "Güzel söz sadakadır.", "kaynak": "Buhârî, Edeb, 34" },
  { "id": 53, "metin": "Şüpheli şeylerden kaçınan kimse, dinini ve ırzını korumuş olur.", "kaynak": "Buhârî, Îmân, 39" },
  { "id": 54, "metin": "İnsanlara (hayrı) öğreten kimseye, denizdeki balıklara varıncaya kadar her şey istiğfar eder.", "kaynak": "Tirmizî, İlim, 19" },
  { "id": 55, "metin": "Oruç bir kalkandır. Oruçlu, saygısızlık yapmasın, kötü söz söylemesin.", "kaynak": "Buhârî, Savm, 2" },
  { "id": 56, "metin": "Kim bir oruçluya iftar ettirirse, kendisine onun sevabı kadar sevap yazılır.", "kaynak": "Tirmizî, Savm, 82" },
  { "id": 57, "metin": "Merhamet edene Rahman da merhamet eder.", "kaynak": "Tirmizî, Birr, 16" },
  { "id": 58, "metin": "Üç dua vardır ki şüphesiz kabul edilir: Mazlumun duası, yolcunun duası ve babanın evladına duası.", "kaynak": "İbn Mâce, Dua, 11" },
  { "id": 59, "metin": "Kıyamet gününde müminin mizanında güzel ahlaktan daha ağır basacak bir şey yoktur.", "kaynak": "Tirmizî, Birr, 62" },
  { "id": 60, "metin": "Allah güzeldir, güzelliği sever.", "kaynak": "Müslim, Îmân, 147" },
  { "id": 61, "metin": "İnsanların arasını düzelten, hayır söyleyen kimse yalancı değildir.", "kaynak": "Buhârî, Sulh, 2" },
  { "id": 62, "metin": "Müslümanın hakkı beştir: Selamını almak, hastayı ziyaret, cenazeye katılmak, davete icabet, aksırana dua etmek.", "kaynak": "Buhârî, Cenâiz, 2" },
  { "id": 63, "metin": "Küçüğümüze merhamet etmeyen, büyüğümüze saygı göstermeyen bizden değildir.", "kaynak": "Tirmizî, Birr, 15" },
  { "id": 64, "metin": "İki nimet vardır ki insanların çoğu onların kıymetini bilmez: Sağlık ve boş vakit.", "kaynak": "Buhârî, Rikâk, 1" },
  { "id": 65, "metin": "Allah sizin dış görünüşünüze ve mallarınıza bakmaz, fakat kalplerinize ve amellerinize bakar.", "kaynak": "Müslim, Birr, 34" },
  { "id": 66, "metin": "Kişi sevdiği ile beraberdir.", "kaynak": "Buhârî, Edeb, 96" },
  { "id": 67, "metin": "Zannın çoğundan sakınınız. Çünkü zan, sözlerin en yalanıdır.", "kaynak": "Buhârî, Vasâyâ, 8" },
  { "id": 68, "metin": "Sadaka vermek malı eksiltmez.", "kaynak": "Müslim, Birr, 69" },
  { "id": 69, "metin": "Sizin en hayırlınız, borcunu en güzel şekilde ödeyendir.", "kaynak": "Buhârî, İstikrâz, 4" },
  { "id": 70, "metin": "Kim (din) kardeşinin bir ihtiyacını giderirse Allah da onun bir ihtiyacını giderir.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 71, "metin": "Yolculuk, azaptan bir parçadır.", "kaynak": "Buhârî, Umre, 19" },
  { "id": 72, "metin": "Dünyada bir garip (yolcu) gibi yahut gelip geçen bir kimse gibi ol.", "kaynak": "Buhârî, Rikâk, 3" },
  { "id": 73, "metin": "Ölüyü (kabre kadar) üç şey takip eder: Ailesi, malı ve ameli. İkisi döner, ameli kalır.", "kaynak": "Buhârî, Rikâk, 42" },
  { "id": 74, "metin": "Cehennem nefse hoş gelen şeylerle; cennet ise nefse zor gelen şeylerle kuşatılmıştır.", "kaynak": "Buhârî, Rikâk, 28" },
  { "id": 75, "metin": "Kim bir hayra öncülük ederse, onu yapanın sevabı gibi sevap alır.", "kaynak": "Müslim, İmare, 133" },
  { "id": 76, "metin": "Müminler, birbirlerini sevmede ve merhamet etmede bir vücut gibidirler.", "kaynak": "Buhârî, Edeb, 27" },
  { "id": 77, "metin": "Üzerine güneşin doğduğu en hayırlı gün Cuma günüdür.", "kaynak": "Müslim, Cuma, 17" },
  { "id": 78, "metin": "Kim Cuma günü guslederse, günahlarına kefaret olur.", "kaynak": "Buhârî, Cuma, 2" },
  { "id": 79, "metin": "Akrabasıyla ilgisini kesen kimse cennete giremez.", "kaynak": "Buhârî, Edeb, 11" },
  { "id": 80, "metin": "Sözü, işinden fazla olan kimse kınanmıştır.", "kaynak": "Müsned, 2/160" },
  { "id": 81, "metin": "Her dinin bir ahlakı vardır; İslam'ın ahlakı da hayadır.", "kaynak": "İbn Mâce, Zühd, 17" },
  { "id": 82, "metin": "Yedi helak ediciden sakının: Şirk, büyü, cana kıymak, faiz, yetim malı, savaştan kaçmak, iftira.", "kaynak": "Buhârî, Vesâyâ, 23" },
  { "id": 83, "metin": "Sizin en hayırlınız, ailesine karşı en hayırlı olanınızdır.", "kaynak": "Tirmizî, Menâkıb, 63" },
  { "id": 84, "metin": "Cennet annelerin ayakları altındadır.", "kaynak": "Nesâî, Cihâd, 6" },
  { "id": 85, "metin": "Allah'ım! Fayda vermeyen ilimden, huşu duymayan kalpten, kabul edilmeyen duadan sana sığınırım.", "kaynak": "Müslim, Zikir, 73" },
  { "id": 86, "metin": "Kim bana bir defa salavat getirirse, Allah da ona on defa rahmet eder.", "kaynak": "Müslim, Salât, 70" },
  { "id": 87, "metin": "İman yetmiş küsur şubedir. En üstünü 'La ilahe illallah', en düşüğü yoldan eziyeti kaldırmaktır.", "kaynak": "Buhârî, Îmân, 3" },
  { "id": 88, "metin": "Şüphesiz Allah, (kullarını) affedicidir, affetmeyi sever.", "kaynak": "Tirmizî, Deavât, 84" },
  { "id": 89, "metin": "Kim ilim tahsili için bir yola girerse, Allah ona cennetin yolunu kolaylaştırır.", "kaynak": "Müslim, Zikir, 39" },
  { "id": 90, "metin": "İşçiye ücretini teri kurumadan veriniz.", "kaynak": "İbn Mâce, Ruhûn, 4" },
  { "id": 91, "metin": "Bizi küçük gören, bizimle alay eden bizden değildir.", "kaynak": "Tirmizî, Birr, 5" },
  { "id": 92, "metin": "Kim (din) kardeşinin ayıbını örterse, Allah da kıyamet gününde onun ayıbını örter.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 93, "metin": "Amellerin en hayırlısı, az da olsa devamlı olanıdır.", "kaynak": "Buhârî, Îmân, 32" },
  { "id": 94, "metin": "Allah'a en sevimli gelen yerler mescitlerdir.", "kaynak": "Müslim, Mesâcid, 288" },
  { "id": 95, "metin": "Sabır, (musibetin geldiği) ilk andadır.", "kaynak": "Buhârî, Cenâiz, 32" },
  { "id": 96, "metin": "Mümin, yeşil ekine benzer. Rüzgar onu eğer ama yıkamaz, yine doğrulur.", "kaynak": "Buhârî, Tevhîd, 31" },
  { "id": 97, "metin": "Kim bir iyilik yaparsa ona on katı vardır.", "kaynak": "En'âm Suresi, 160 (Ayet meali destekli hadis)" },
  { "id": 98, "metin": "Kıyamet kopsa bile, elinizde bir fidan varsa onu dikiniz.", "kaynak": "Müsned, 3/191" },
  { "id": 99, "metin": "Söz taşıyanlar (cezalarını çekmeden) cennete giremezler.", "kaynak": "Buhârî, Edeb, 50" },
  { "id": 100, "metin": "Size iki şey bırakıyorum: Allah'ın Kitabı ve Peygamberinin Sünneti.", "kaynak": "Muvatta, Kader, 3" },
  { "id": 101, "metin": "Sizden biriniz bir münker (kötülük) gördüğü zaman onu eliyle düzeltsin.", "kaynak": "Müslim, Îmân, 78" },
  { "id": 102, "metin": "Doğru sözlü ve güvenilir tüccar, (kıyamet gününde) peygamberler, sıddıklar ve şehitlerle beraberdir.", "kaynak": "Tirmizî, Büyû, 4" },
  { "id": 103, "metin": "Kim (din) kardeşinin onurunu korursa, Allah da kıyamet gününde onun yüzünü cehennem ateşinden korur.", "kaynak": "Tirmizî, Birr, 20" },
  { "id": 104, "metin": "Zenginlik mal çokluğuyla değil, gönül zenginliğiyledir.", "kaynak": "Buhârî, Rikâk, 15" },
  { "id": 105, "metin": "Kıyamet gününde kulun ilk hesaba çekileceği ameli namazıdır.", "kaynak": "Tirmizî, Salât, 188" },
  { "id": 106, "metin": "Allah'a ve ahiret gününe iman eden kimse komşusuna eziyet etmesin.", "kaynak": "Buhârî, Edeb, 31" },
  { "id": 107, "metin": "Mümin, kınayıcı, lanet edici, kaba ve çirkin sözlü olamaz.", "kaynak": "Tirmizî, Birr, 48" },
  { "id": 108, "metin": "Kim bir iyiliğe vesile olursa, ona o iyiliği yapanın ecri kadar sevap vardır.", "kaynak": "Müslim, İmare, 133" },
  { "id": 109, "metin": "Söz taşıyan (koğuculuk yapan) cennete giremez.", "kaynak": "Buhârî, Edeb, 50" },
  { "id": 110, "metin": "Merhamet etmeyene merhamet olunmaz.", "kaynak": "Müslim, Fezâil, 66" },
  { "id": 111, "metin": "Müslümana sövmek fısk (günah), onu öldürmek küfürdür.", "kaynak": "Buhârî, Îmân, 36" },
  { "id": 112, "metin": "Akrabalık bağlarını kesen cennete giremez.", "kaynak": "Buhârî, Edeb, 11" },
  { "id": 113, "metin": "Bizi aldatan bizden değildir.", "kaynak": "Müslim, Îmân, 164" },
  { "id": 114, "metin": "İki yüzlülerin kıyamet gününde Allah katında en kötü insanlar olduğunu göreceksiniz.", "kaynak": "Buhârî, Edeb, 52" },
  { "id": 115, "metin": "Allah'tan korkun ve çocuklarınız arasında adaletli davranın.", "kaynak": "Buhârî, Hibe, 12" },
  { "id": 116, "metin": "Zulüm, kıyamet gününde karanlıklar olacaktır.", "kaynak": "Buhârî, Mezâlim, 8" },
  { "id": 117, "metin": "Kim bir yolu, ilim aramak için tutarsa, Allah ona cennet yolunu kolaylaştırır.", "kaynak": "Tirmizî, İlim, 2" },
  { "id": 118, "metin": "Sadaka, suyun ateşi söndürdüğü gibi hataları söndürür (yok eder).", "kaynak": "Tirmizî, Cum'a, 79" },
  { "id": 119, "metin": "Oruçlunun uykusu ibadet, susması tesbihtir.", "kaynak": "Deylemî, Müsned, 4/333" },
  { "id": 120, "metin": "En faziletli ibadet, dua etmektir.", "kaynak": "Hâkim, Müstedrek, 1/491" },
  { "id": 121, "metin": "Yemeği topluca yiyiniz; bereket toplulukta (beraber yemekte)dir.", "kaynak": "İbn Mâce, Et'ime, 17" },
  { "id": 122, "metin": "Sizden biri aksırıp 'Elhamdülillah' derse, ona 'Yerhamükellah' deyiniz.", "kaynak": "Buhârî, Edeb, 125" },
  { "id": 123, "metin": "Misvak kullanın, çünkü misvak ağzı temizler, Rabbin rızasını kazandırır.", "kaynak": "Nesâî, Tahâret, 5" },
  { "id": 124, "metin": "Beş vakit namaz, büyük günahlardan kaçınıldığı takdirde, aralarında işlenen küçük günahlara kefarettir.", "kaynak": "Müslim, Tahâret, 16" },
  { "id": 125, "metin": "Cemaat rahmettir, tefrika (ayrılık) ise azaptır.", "kaynak": "Müsned, 4/375" },
  { "id": 126, "metin": "İşler, ehline verilmediği zaman kıyameti bekle.", "kaynak": "Buhârî, İlim, 2" },
  { "id": 127, "metin": "İman, sabır ve hoşgörüdür.", "kaynak": "Müsned, 4/385" },
  { "id": 128, "metin": "Kıyamet günü, müminin terazisinde güzel ahlaktan daha ağır basan bir şey yoktur.", "kaynak": "Tirmizî, Birr, 62" },
  { "id": 129, "metin": "Kişi, dostunun dini üzeredir. Öyleyse her biriniz, kiminle dostluk ettiğine dikkat etsin.", "kaynak": "Ebû Dâvûd, Edeb, 16" },
  { "id": 130, "metin": "Mümin, saf ve temizdir; günahkar münafık ise kurnaz ve hilekardır.", "kaynak": "Tirmizî, Birr, 41" },
  { "id": 131, "metin": "Allah temizdir, temizliği sever.", "kaynak": "Tirmizî, Edeb, 41" },
  { "id": 132, "metin": "Biriniz esnediği zaman elini ağzına koysun.", "kaynak": "Müslim, Zühd, 57" },
  { "id": 133, "metin": "Müslüman, Müslümanın kardeşidir. Ona zulmetmez, onu (düşmana) teslim etmez.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 134, "metin": "Kim Allah'a ve ahiret gününe inanıyorsa misafirine ikram etsin.", "kaynak": "Buhârî, Edeb, 85" },
  { "id": 135, "metin": "Kim, insanların kızdırması pahasına Allah'ı memnun etmeye çalışırsa, Allah onu insanlara muhtaç etmez.", "kaynak": "Tirmizî, Zühd, 64" },
  { "id": 136, "metin": "Allah, her işte yumuşaklığı sever.", "kaynak": "Buhârî, İstitâbe, 4" },
  { "id": 137, "metin": "Öfkelendiğin zaman sus.", "kaynak": "Müsned, 1/239" },
  { "id": 138, "metin": "Yedi sınıf insan vardır ki, Allah onları kendi gölgesinden başka gölge bulunmayan günde (kıyamette) gölgelendirir.", "kaynak": "Buhârî, Ezân, 36" },
  { "id": 139, "metin": "Allah katında en sevimli amel, az da olsa devamlı olanıdır.", "kaynak": "Buhârî, Rikâk, 18" },
  { "id": 140, "metin": "Kim Cuma namazına giderken guslederse, günahlarından arınmış olur.", "kaynak": "Müslim, Cuma, 5" },
  { "id": 141, "metin": "Hediyeleşin, çünkü hediye kalpteki kini giderir.", "kaynak": "Tirmizî, Velâ, 6" },
  { "id": 142, "metin": "Dul kadınlara ve yoksullara yardım eden kimse, Allah yolunda cihat eden gibidir.", "kaynak": "Buhârî, Nafakât, 1" },
  { "id": 143, "metin": "Yetimi koruyup kollayanla ben, cennette şu iki parmak gibiyiz.", "kaynak": "Buhârî, Edeb, 24" },
  { "id": 144, "metin": "Müminler arasında imanı en kamil olanı, ahlakı en güzel olanıdır.", "kaynak": "Tirmizî, Radâ, 11" },
  { "id": 145, "metin": "Kim susarsa kurtulur.", "kaynak": "Tirmizî, Kıyâmet, 50" },
  { "id": 146, "metin": "Her kim bir Müslümanın ayıbını örterse, Allah da dünya ve ahirette onun ayıbını örter.", "kaynak": "Müslim, Zikir, 38" },
  { "id": 147, "metin": "Allah'tan korkun ve (dargın olduğunuz) aranızı düzeltin.", "kaynak": "Enfâl Suresi, 1 (Ayet destekli hadis)" },
  { "id": 148, "metin": "Allah, sizin suretlerinize ve mallarınıza bakmaz, ancak kalplerinize ve amellerinize bakar.", "kaynak": "Müslim, Birr, 33" },
  { "id": 149, "metin": "İnsanoğlunun her bir eklemi için her gün bir sadaka vermesi gerekir.", "kaynak": "Buhârî, Sulh, 11" },
  { "id": 150, "metin": "Güzel söz söylemek sadakadır.", "kaynak": "Buhârî, Cihâd, 128" },
  { "id": 151, "metin": "Namaz, dinin direğidir.", "kaynak": "Aclûnî, Keşfü'l-Hafâ, 2/31" },
  { "id": 152, "metin": "Cennet, kılıçların gölgesi altındadır.", "kaynak": "Buhârî, Cihâd, 22" },
  { "id": 153, "metin": "Müslüman, Müslümanın kardeşidir; ona hıyanet etmez, ona yalan söylemez, onu yüzüstü bırakmaz.", "kaynak": "Tirmizî, Birr, 18" },
  { "id": 154, "metin": "Sizden biri, kendisi için sevip istediği şeyi, kardeşi için de sevip istemedikçe gerçek mümin olamaz.", "kaynak": "Buhârî, Îmân, 7" },
  { "id": 155, "metin": "Komşusu açken tok yatan (gerçek) mümin değildir.", "kaynak": "Hâkim, Müstedrek, 2/15" },
  { "id": 156, "metin": "İyilik, yüzlerinizi doğu ve batı tarafına çevirmeniz değildir.", "kaynak": "Bakara Suresi, 177 (Ayet destekli hadis)" },
  { "id": 157, "metin": "Allah, işini güzel yapanı sever.", "kaynak": "Taberânî, el-Mu'cemü'l-Evsat, 1/275" },
  { "id": 158, "metin": "Herkesin hatası vardır. Hata edenlerin en hayırlısı tövbe edenlerdir.", "kaynak": "Tirmizî, Kıyâmet, 49" },
  { "id": 159, "metin": "Şüpheli şeylerden sakın, şüphe vermeyen şeye yönel.", "kaynak": "Tirmizî, Kıyâmet, 60" },
  { "id": 160, "metin": "Allah Teala kıskançtır. Allah'ın kıskanması, haram kıldığı şeyleri kulun işlemesidir.", "kaynak": "Buhârî, Nikâh, 107" },
  { "id": 161, "metin": "Kıyamet gününde şehidin kanı, alimin mürekkebi ile tartılır; alimin mürekkebi ağır gelir.", "kaynak": "Suyûtî, el-Câmiu's-Sağîr, 2/655" },
  { "id": 162, "metin": "Dünya sevgisi, her hatanın başıdır.", "kaynak": "Beyhakî, Şuabü'l-İmân, 7/338" },
  { "id": 163, "metin": "Kim sabah namazını kılarsa, o Allah'ın güvencesindedir.", "kaynak": "Müslim, Mesâcid, 262" },
  { "id": 164, "metin": "Sizin en hayırlınız, kadınlarına karşı en hayırlı olanınızdır.", "kaynak": "Tirmizî, Radâ, 11" },
  { "id": 165, "metin": "Kadınlar, erkeklerin benzerleridir (hak ve sorumlulukta eşittirler).", "kaynak": "Ebû Dâvûd, Tahâret, 94" },
  { "id": 166, "metin": "İki kişi bir araya gelince, üçüncüyü bırakıp fısıldaşmasınlar; bu onu üzer.", "kaynak": "Buhârî, İsti'zân, 47" },
  { "id": 167, "metin": "Kim, (din) kardeşine haksızlık etmişse, kıyamet günü gelmeden onunla helalleşsin.", "kaynak": "Buhârî, Mezâlim, 10" },
  { "id": 168, "metin": "Yalan yere yemin etmek, malın sürümünü artırır fakat bereketini yok eder.", "kaynak": "Buhârî, Büyû, 26" },
  { "id": 169, "metin": "Her ümmetin bir fitnesi (imtihanı) vardır; benim ümmetimin fitnesi de maldır.", "kaynak": "Tirmizî, Zühd, 26" },
  { "id": 170, "metin": "Allah'ım! Beni iyilik işledikleri zaman sevinen, kötülük işledikleri zaman istiğfar edenlerden eyle.", "kaynak": "İbn Mâce, Edeb, 57" },
  { "id": 171, "metin": "Müminler, tuğlaları birbirine kenetlenmiş bina gibidirler.", "kaynak": "Buhârî, Salât, 88" },
  { "id": 172, "metin": "Sadakanın en faziletlisi, kişinin (ailesine harcamak üzere) kazandığı maldan vermesidir.", "kaynak": "Müsned, 2/358" },
  { "id": 173, "metin": "Yol sormak, ilmin yarısıdır.", "kaynak": "Taberânî (Zayıf senetle rivayet edilse de manaen sahihtir)" },
  { "id": 174, "metin": "Allah katında arkadaşların en hayırlısı, arkadaşına en hayırlı olandır.", "kaynak": "Tirmizî, Birr, 28" },
  { "id": 175, "metin": "Komşuların en hayırlısı, komşusuna en hayırlı olandır.", "kaynak": "Tirmizî, Birr, 28" },
  { "id": 176, "metin": "Kim Allah'a kavuşmayı severse, Allah da ona kavuşmayı sever.", "kaynak": "Buhârî, Rikâk, 41" },
  { "id": 177, "metin": "Mümin, kılıcıyla ve diliyle cihat eder.", "kaynak": "Müsned, 3/460" },
  { "id": 178, "metin": "Sizden biri, ayakta su içmesin.", "kaynak": "Müslim, Eşribe, 112" },
  { "id": 179, "metin": "İçki, bütün kötülüklerin anasıdır.", "kaynak": "Nesâî, Eşribe, 44" },
  { "id": 180, "metin": "Kim bir kavme (topluluğa) benzerse, o da onlardandır.", "kaynak": "Ebû Dâvûd, Libâs, 4" },
  { "id": 181, "metin": "Lanet edilenler, kıyamet gününde ne şefaatçi ne de şahit olabilirler.", "kaynak": "Müslim, Birr, 85" },
  { "id": 182, "metin": "Kıskançlık, ateşin odunu yediği gibi iyilikleri yer bitirir.", "kaynak": "Ebû Dâvûd, Edeb, 44" },
  { "id": 183, "metin": "Ümmetimden bir taife, hak üzere olmaya devam edecektir.", "kaynak": "Müslim, İmare, 170" },
  { "id": 184, "metin": "Amellerin sonucu (son nefese) göredir.", "kaynak": "Buhârî, Kader, 5" },
  { "id": 185, "metin": "Şehit, (kul hakkı hariç) her günahı affedilir.", "kaynak": "Müslim, İmare, 112" },
  { "id": 186, "metin": "Sizin en hayırlınız, Kuran'ı öğrenen ve öğreteninizdir.", "kaynak": "Buhârî, Fedâilü'l-Kur'ân, 21" },
  { "id": 187, "metin": "Bir saatlik tefekkür, bir yıllık (nafile) ibadetten hayırlıdır.", "kaynak": "Aclûnî, Keşfü'l-Hafâ, 1/310" },
  { "id": 188, "metin": "Kim namazı kasten terk ederse, (manevi bakımdan) küfre düşmüş olur.", "kaynak": "Müslim, Îmân, 134" },
  { "id": 189, "metin": "Kıyamet gününde insanın ayakları, ömrünü nerede tükettiğinden sorulmadıkça yerinden ayrılmaz.", "kaynak": "Tirmizî, Kıyâmet, 1" },
  { "id": 190, "metin": "Gençliğini ibadetle geçiren genci, Allah (arşının) gölgesinde gölgelendirir.", "kaynak": "Buhârî, Ezân, 36" },
  { "id": 191, "metin": "Bela, müminin sabrını denemek içindir.", "kaynak": "Tirmizî, Zühd, 56" },
  { "id": 192, "metin": "Allah, kulunun tövbesinden, (çölde) devesini kaybedip bulan kimseden daha çok hoşnut olur.", "kaynak": "Müslim, Tövbe, 1" },
  { "id": 193, "metin": "Dünya malı tatlı ve çekicidir.", "kaynak": "Buhârî, Cihâd, 37" },
  { "id": 194, "metin": "Kibir, hakkı inkar etmek ve insanları küçümsemektir.", "kaynak": "Müslim, Îmân, 147" },
  { "id": 195, "metin": "Kim ilim yolunda olursa, Allah ona cenneti kolaylaştırır.", "kaynak": "Tirmizî, İlim, 19" },
  { "id": 196, "metin": "Müslüman, elinden ve dilinden Müslümanların emin olduğu kimsedir.", "kaynak": "Buhârî, Îmân, 4" },
  { "id": 197, "metin": "Her duyduğunu söylemesi, kişiye yalan olarak yeter.", "kaynak": "Müslim, Mukaddime, 5" },
  { "id": 198, "metin": "İyilik, (insanın) kalbini huzura kavuşturan şeydir.", "kaynak": "Müsned, 4/227" },
  { "id": 199, "metin": "Allah'tan hakkıyla haya edin.", "kaynak": "Tirmizî, Kıyâmet, 24" },
  { "id": 200, "metin": "Kim, Allah'ın rızasını gözeterek bir mescit yaptırırsa, Allah da ona cennette bir köşk yaptırır.", "kaynak": "Buhârî, Salât, 65" },
  { "id": 201, "metin": "Misvak kullanın; çünkü misvak ağzı temizler, Rabbin rızasını kazandırır.", "kaynak": "Nesâî, Tahâret, 5" },
  { "id": 202, "metin": "Ezanı duyduğunuz zaman, müezzinin dediklerini siz de tekrar edin.", "kaynak": "Buhârî, Ezân, 7" },
  { "id": 203, "metin": "Ezan ile kamet arasında yapılan dua reddolunmaz.", "kaynak": "Tirmizî, Salât, 44" },
  { "id": 204, "metin": "Namazda saflarınızı düzeltin; çünkü safları düzeltmek namazın kemalindendir.", "kaynak": "Buhârî, Ezân, 74" },
  { "id": 205, "metin": "Kulun Rabbine en yakın olduğu an, secde anıdır. Orada duayı çokça yapın.", "kaynak": "Müslim, Salât, 215" },
  { "id": 206, "metin": "Allah, tekdir ve teki (vitri) sever.", "kaynak": "Buhârî, Deavât, 69" },
  { "id": 207, "metin": "Her kim sabah namazını kılar ve güneş doğana kadar Allah'ı zikrederse, tam bir hac ve umre sevabı alır.", "kaynak": "Tirmizî, Cum'a, 59" },
  { "id": 208, "metin": "Cuma gününde bir saat vardır ki, Müslüman bir kul o saate denk gelip Allah'tan bir hayır isterse, Allah ona dilediğini verir.", "kaynak": "Buhârî, Cum'a, 37" },
  { "id": 209, "metin": "Kim bir cenaze namazına katılırsa ona bir kırat (Uhud dağı kadar) sevap vardır.", "kaynak": "Buhârî, Cenâiz, 58" },
  { "id": 210, "metin": "Kabirleri ziyaret edin; çünkü kabir ziyareti size ahireti hatırlatır.", "kaynak": "Müslim, Cenâiz, 106" },
  { "id": 211, "metin": "Zekatı verilmeyen mal, kıyamet gününde sahibi için zehirli bir yılan olur.", "kaynak": "Buhârî, Zekât, 3" },
  { "id": 212, "metin": "Sahur yapınız, zira sahurda bereket vardır.", "kaynak": "Buhârî, Savm, 20" },
  { "id": 213, "metin": "İnsanlar iftarı acele yaptıkları sürece hayır üzere olmaya devam ederler.", "kaynak": "Buhârî, Savm, 45" },
  { "id": 214, "metin": "Kim yalan söylemeyi ve yalanla iş yapmayı bırakmazsa, Allah'ın onun yemeyi içmeyi bırakmasına (oruç tutmasına) ihtiyacı yoktur.", "kaynak": "Buhârî, Savm, 8" },
  { "id": 215, "metin": "Kadir gecesini Ramazan'ın son on gününde arayın.", "kaynak": "Buhârî, Leyletü'l-kadr, 3" },
  { "id": 216, "metin": "Hac, Arafat'tır (Arafat'ta vakfeye durmaktır).", "kaynak": "Tirmizî, Hac, 57" },
  { "id": 217, "metin": "Zemzem suyu, ne niyetle içilirse onun içindir.", "kaynak": "İbn Mâce, Menâsik, 78" },
  { "id": 218, "metin": "Medine'nin sıkıntısına ve zorluğuna sabreden kimseye, kıyamet gününde şefaatçi olurum.", "kaynak": "Müslim, Hac, 483" },
  { "id": 219, "metin": "Kuran okuyan mümin, tadı ve kokusu güzel olan turunçgil gibidir.", "kaynak": "Buhârî, Fedâilü'l-Kur'ân, 17" },
  { "id": 220, "metin": "Fatiha Suresi her derde şifadır.", "kaynak": "Dârimî, Fedâilü'l-Kur'ân, 12" },
  { "id": 221, "metin": "Kuran'da otuz ayetlik bir sure vardır (Mülk Suresi), okuyana şefaat eder ve günahları bağışlanır.", "kaynak": "Tirmizî, Fedâilü'l-Kur'ân, 9" },
  { "id": 222, "metin": "Evlerinizi kabirlere çevirmeyin. Şüphesiz şeytan, içinde Bakara Suresi okunan evden kaçar.", "kaynak": "Müslim, Müsâfirîn, 212" },
  { "id": 223, "metin": "Allah'ın doksan dokuz ismi vardır. Kim bunları ezberleyip (hayatına yansıtırsa) cennete girer.", "kaynak": "Buhârî, Deavât, 68" },
  { "id": 224, "metin": "Allah mahlukatı yarattığı zaman, 'Rahmetim gazabımı geçmiştir' diye yazdı.", "kaynak": "Buhârî, Tevhîd, 15" },
  { "id": 225, "metin": "Allah'ın, kulunun tövbesine sevinmesi, birinizin çölde kaybettiği devesini bulmasına sevinmesinden daha fazladır.", "kaynak": "Müslim, Tövbe, 1" },
  { "id": 226, "metin": "Kim günde yüz defa 'Sübhanallahi ve bihamdihi' derse, günahları deniz köpüğü kadar da olsa dökülür.", "kaynak": "Buhârî, Deavât, 65" },
  { "id": 227, "metin": "'La havle ve la kuvvete illa billah' sözü, cennet hazinelerinden bir hazinedir.", "kaynak": "Buhârî, Deavât, 50" },
  { "id": 228, "metin": "Zikrin en faziletlisi 'La ilahe illallah', duanın en faziletlisi 'Elhamdülillah'tır.", "kaynak": "Tirmizî, Deavât, 9" },
  { "id": 229, "metin": "Yatağına girdiğinde Ayete'l-Kürsi'yi oku, sabaha kadar seni koruyan bir melek verilir.", "kaynak": "Buhârî, Vekâlet, 10" },
  { "id": 230, "metin": "Kim yemeği yedikten sonra 'Bana bu yemeği yediren Allah'a hamdolsun' derse geçmiş günahları bağışlanır.", "kaynak": "Tirmizî, Deavât, 56" },
  { "id": 231, "metin": "Yeni bir elbise giydiğinde Allah'a hamdet.", "kaynak": "Ebû Dâvûd, Libâs, 1" },
  { "id": 232, "metin": "Yol üzerinden eziyet veren şeyleri kaldırmak sadakadır.", "kaynak": "Buhârî, Cihâd, 128" },
  { "id": 233, "metin": "Ey insanlar! Selamı yayın, yemek yedirin, akrabalarınızı gözetin.", "kaynak": "İbn Mâce, Et'ime, 1" },
  { "id": 234, "metin": "İki Müslüman karşılaşıp el sıkışırlarsa, ayrılmadan önce günahları bağışlanır.", "kaynak": "Ebû Dâvûd, Edeb, 142" },
  { "id": 235, "metin": "Öfke şeytandandır, şeytan ateşten yaratılmıştır. Öfkelendiğiniz zaman abdest alın.", "kaynak": "Ebû Dâvûd, Edeb, 3" },
  { "id": 236, "metin": "Ben, şaka bile olsa yalan söylemeyen kimseye cennetin ortasında bir köşk kefiliyim.", "kaynak": "Ebû Dâvûd, Edeb, 7" },
  { "id": 237, "metin": "Haklı bile olsa tartışmayı terk eden kimseye cennetin kenarında bir köşk verilir.", "kaynak": "Ebû Dâvûd, Edeb, 7" },
  { "id": 238, "metin": "Kalbinde zerre kadar kibir bulunan kimse cennete giremez.", "kaynak": "Müslim, Îmân, 147" },
  { "id": 239, "metin": "Sadece iki kişiye gıpta edilir: Allah'ın verdiği malı hak yolunda harcayan ve Allah'ın verdiği ilimle amel eden.", "kaynak": "Buhârî, İlim, 15" },
  { "id": 240, "metin": "Birbirinizin kusurlarını araştırmayın, birbirinizin özel hallerini casus gibi takip etmeyin.", "kaynak": "Buhârî, Nikâh, 45" },
  { "id": 241, "metin": "Müslümanların en hayırlısı, iki yüzlü olmayan kimsedir.", "kaynak": "Buhârî, Edeb, 52" },
  { "id": 242, "metin": "Ölüye sövmeyiniz; çünkü onlar yaptıklarının karşılığına ulaşmışlardır.", "kaynak": "Buhârî, Cenâiz, 97" },
  { "id": 243, "metin": "Kim, anne ve babasının dostlarını ziyaret ederse, en büyük iyiliği yapmış olur.", "kaynak": "Müslim, Birr, 11" },
  { "id": 244, "metin": "Teyze, anne yerindedir.", "kaynak": "Buhârî, Sulh, 6" },
  { "id": 245, "metin": "Saçı sakalı ağarmış yaşlı Müslümana saygı göstermek, Allah'a duyulan saygıdandır.", "kaynak": "Ebû Dâvûd, Edeb, 20" },
  { "id": 246, "metin": "Çocukları sevin, onlara karşı şefkatli olun.", "kaynak": "Buhârî, Edeb, 18" },
  { "id": 247, "metin": "Kim üç kız çocuğunu veya kız kardeşini yetiştirir, onlara iyi davranırsa cennet onundur.", "kaynak": "Tirmizî, Birr, 13" },
  { "id": 248, "metin": "Hizmetçilerinize yediğinizden yedirin, giydiğinizden giydirin.", "kaynak": "Buhârî, Itk, 15" },
  { "id": 249, "metin": "Bir kadın, ölünceye kadar hapsettiği bir kedi yüzünden cehenneme girdi.", "kaynak": "Buhârî, Bedü'l-halk, 16" },
  { "id": 250, "metin": "Susuzluktan dili sarkan bir köpeğe su veren adamın günahları bağışlandı.", "kaynak": "Buhârî, Vudû, 33" },
  { "id": 251, "metin": "Binek hayvanlarının sırtını kürsü (sandalye) edinmeyin.", "kaynak": "Müsned, 3/439" },
  { "id": 252, "metin": "Zengin olduğu halde borcunu ödemeyi geciktirmek zulümdür.", "kaynak": "Müslim, Müsâkât, 33" },
  { "id": 253, "metin": "Verdiği sadakayı geri isteyen kimse, kustuğunu yalayan köpek gibidir.", "kaynak": "Buhârî, Hibe, 14" },
  { "id": 254, "metin": "Haramla beslenen vücut cennete giremez.", "kaynak": "Beyhakî, Şuabü'l-İmân, 5/56" },
  { "id": 255, "metin": "Allah, faiz yiyeni, yedireni, şahitlerini ve yazanını lanetlemiştir.", "kaynak": "Müslim, Müsâkât, 106" },
  { "id": 256, "metin": "Rüşvet alan da veren de lanetlenmiştir.", "kaynak": "Tirmizî, Ahkâm, 9" },
  { "id": 257, "metin": "Kim haksız yere bir karış toprak gasp ederse, kıyamet günü o toprak yedi kat olarak boynuna dolanır.", "kaynak": "Buhârî, Mezâlim, 13" },
  { "id": 258, "metin": "Kim kendini bir şeyle öldürürse, kıyamet gününde o şeyle azap olunur.", "kaynak": "Buhârî, Eymân, 7" },
  { "id": 259, "metin": "Kim bir falcıya gidip bir şey sorarsa, kırk gece namazı kabul olmaz.", "kaynak": "Müslim, Selâm, 125" },
  { "id": 260, "metin": "Melekler, içinde (canlı) suret ve köpek bulunan eve girmezler.", "kaynak": "Buhârî, Libâs, 88" },
  { "id": 261, "metin": "Nazar haktır (gerçektir).", "kaynak": "Müslim, Selâm, 41" },
  { "id": 262, "metin": "Deveni bağla, sonra Allah'a tevekkül et.", "kaynak": "Tirmizî, Kıyâmet, 60" },
  { "id": 263, "metin": "Veba (salgın hastalık), her Müslüman için bir şehitliktir.", "kaynak": "Buhârî, Cihâd, 30" },
  { "id": 264, "metin": "Allah yolunda ayakları tozlanan kimseye cehennem ateşi haramdır.", "kaynak": "Buhârî, Cihâd, 16" },
  { "id": 265, "metin": "Bir gün ve bir gece nöbet tutmak, bir ay oruç tutup gecesini ibadetle geçirmekten hayırlıdır.", "kaynak": "Müslim, İmare, 163" },
  { "id": 266, "metin": "Cennette Reyyan denilen bir kapı vardır ki, kıyamet gününde oradan sadece oruçlular girer.", "kaynak": "Buhârî, Savm, 4" },
  { "id": 267, "metin": "Sizin şu (dünya) ateşiniz, cehennem ateşinin yetmiş parçasından bir parçadır.", "kaynak": "Buhârî, Bedü'l-halk, 10" },
  { "id": 268, "metin": "Şefaatim, ümmetimden büyük günah işleyenleredir.", "kaynak": "Tirmizî, Kıyâmet, 11" },
  { "id": 269, "metin": "Kalbinde zerre kadar iman olan kimse (eninde sonunda) cehennemden çıkacaktır.", "kaynak": "Buhârî, Îmân, 33" },
  { "id": 270, "metin": "Siz Rabbinizi, şu ayı (dolunayı) gördüğünüz gibi (cennette) göreceksiniz.", "kaynak": "Buhârî, Mevâkît, 16" },
  { "id": 271, "metin": "Zaman kısalıp, ameller azalmadıkça kıyamet kopmaz.", "kaynak": "Buhârî, Fiten, 25" },
  { "id": 272, "metin": "Güneş batıdan doğmadıkça kıyamet kopmaz. O doğduğunda artık iman etmenin faydası olmaz.", "kaynak": "Buhârî, Tefsîr, 6" },
  { "id": 273, "metin": "Nefsim kudret elinde olan Allah'a yemin ederim ki, Meryem oğlu İsa adaletli bir hakem olarak inecektir.", "kaynak": "Buhârî, Büyû, 102" },
  { "id": 274, "metin": "Ölümü temenni etmeyin; eğer iyi biriyseniz hayrınız artar, kötü biriyseniz tövbe edersiniz.", "kaynak": "Buhârî, Temennî, 6" },
  { "id": 275, "metin": "Kimin son sözü 'La ilahe illallah' olursa cennete girer.", "kaynak": "Ebû Dâvûd, Cenâiz, 20" },
  { "id": 276, "metin": "Kabir azabı haktır (gerçektir).", "kaynak": "Buhârî, Cenâiz, 87" },
  { "id": 277, "metin": "Ademoğlu yaşlanır ama onda iki şey genç kalır: Hırs ve emel (uzun yaşama isteği).", "kaynak": "Buhârî, Rikâk, 5" },
  { "id": 278, "metin": "Akıllı kimse, nefsini hesaba çeken ve ölümden sonrası için çalışandır.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 279, "metin": "Aciz kimse, nefsinin arzularına uyup Allah'tan bağışlanma umandır.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 280, "metin": "İhsan, Allah'ı görüyormuşsun gibi ibadet etmendir. Sen O'nu görmesen de O seni görür.", "kaynak": "Müslim, Îmân, 1" },
  { "id": 281, "metin": "Din nasihattir (samimiyettir): Allah'a, Kitabına, Peygamberine, yöneticilere ve tüm Müslümanlara.", "kaynak": "Müslim, Îmân, 95" },
  { "id": 282, "metin": "Müflis, kıyamet gününde namaz, oruç ve zekatla gelir ama kul hakkı yediği için sevapları alınan kimsedir.", "kaynak": "Müslim, Birr, 59" },
  { "id": 283, "metin": "Mazlumun bedduasından sakın. Çünkü onunla Allah arasında perde yoktur.", "kaynak": "Buhârî, Zekât, 63" },
  { "id": 284, "metin": "Allah (zalime) mühlet verir, fakat yakaladığı zaman asla bırakmaz.", "kaynak": "Buhârî, Tefsîr, 11" },
  { "id": 285, "metin": "Dikkat edin! Cahiliye devrindeki bütün kan davaları kaldırılmıştır.", "kaynak": "Müslim, Hac, 147 (Veda Hutbesi)" },
  { "id": 286, "metin": "Kadınlar hakkında Allah'tan korkun. Onları Allah'ın emaneti olarak aldınız.", "kaynak": "Müslim, Hac, 147" },
  { "id": 287, "metin": "Şeytan, yemek yerken Besmele çekilmezse o yemeğe ortak olur.", "kaynak": "Müslim, Eşribe, 102" },
  { "id": 288, "metin": "Evlerinizi kabirlere çevirmeyin, namaz (nafile) kılın.", "kaynak": "Buhârî, Salât, 52" },
  { "id": 289, "metin": "Müminin niyeti amelinden hayırlıdır.", "kaynak": "Mecmeu'z-Zevâid, 1/61" },
  { "id": 290, "metin": "Allah'ın en çok buğzettiği helal, boşanmadır.", "kaynak": "Ebû Dâvûd, Talâk, 3" },
  { "id": 291, "metin": "Biriniz (öfke veya şaka ile) kardeşine silah doğrultmasın.", "kaynak": "Buhârî, Fiten, 7" },
  { "id": 292, "metin": "Kolaylaştırın, zorlaştırmayın; sakin olun, öfkelenmeyin.", "kaynak": "Müslim, Cihâd, 6" },
  { "id": 293, "metin": "Allah bir kulu sevdiği zaman, Cebrail'e 'Ben falanı seviyorum, onu sen de sev' der.", "kaynak": "Buhârî, Bedü'l-halk, 6" },
  { "id": 294, "metin": "Müminler arasında birbirine en merhametli olanlar, imanı en kuvvetli olanlardır.", "kaynak": "Müsned, 2/250" },
  { "id": 295, "metin": "Sizden kimse, kendi nefsi için arzu ettiğini kardeşi için de arzu etmedikçe (kamil) mümin olamaz.", "kaynak": "Buhârî, Îmân, 7" },
  { "id": 296, "metin": "Allah temizlenenleri sever.", "kaynak": "Tevbe Suresi, 108 (Ayet destekli hadis)" },
  { "id": 297, "metin": "Sadaka vermekte acele edin, çünkü bela sadakanın önüne geçemez.", "kaynak": "Taberânî (Hasen hadis)" },
  { "id": 298, "metin": "Kardeşine gülümsemen senin için bir sadakadır.", "kaynak": "Tirmizî, Birr, 36" },
  { "id": 299, "metin": "İman, kalb ile tasdik, dil ile ikrar ve organlarla amel etmektir.", "kaynak": "İbn Mâce, Mukaddime, 9" },
  { "id": 300, "metin": "Allah'ım! Sen affedicisin, kerimsin, affetmeyi seversin, beni de affet.", "kaynak": "Tirmizî, Deavât, 84" },
  { "id": 301, "metin": "Bir Müslümanın, din kardeşine üç günden fazla küsmesi helal değildir.", "kaynak": "Buhârî, Edeb, 62" },
  { "id": 302, "metin": "İki kişi birbirine küserek karşılaşır, biri yüzünü o yana, diğeri bu yana çevirir. Onların en hayırlısı, önce selam verendir.", "kaynak": "Buhârî, Edeb, 62" },
  { "id": 303, "metin": "Müminler kardeştirler. Öyleyse kardeşlerinizin arasını düzeltin.", "kaynak": "Hucurât Suresi, 10 (Ayet destekli hadis)" },
  { "id": 304, "metin": "Her kim Allah'a ve ahiret gününe iman ediyorsa, ya hayır söylesin ya da sussun.", "kaynak": "Müslim, Îmân, 74" },
  { "id": 305, "metin": "Yolların hakkını verin: Gözü haramdan sakınmak, kimseye eziyet etmemek, selamı almak, iyiliği emredip kötülükten sakındırmak.", "kaynak": "Buhârî, Mezâlim, 22" },
  { "id": 306, "metin": "Yazıklar olsun o kimseye ki, insanları güldürmek için konuşur ve yalan söyler! Yazıklar olsun ona, yazıklar olsun!", "kaynak": "Ebû Dâvûd, Edeb, 88" },
  { "id": 307, "metin": "Münafıkların en ağırına giden namaz, yatsı ve sabah namazlarıdır.", "kaynak": "Buhârî, Ezân, 34" },
  { "id": 308, "metin": "Eğer o namazlardaki sevabı bilselerdi, emekleyerek de olsa camiye gelirlerdi.", "kaynak": "Buhârî, Ezân, 34" },
  { "id": 309, "metin": "Kim sabah namazına giderse, her gidiş ve gelişinde Allah ona cennette bir yer hazırlar.", "kaynak": "Buhârî, Ezân, 37" },
  { "id": 310, "metin": "Allah Refîk'tir (yumuşak davranandır), her işte yumuşaklığı sever.", "kaynak": "Buhârî, İstitâbe, 4" },
  { "id": 311, "metin": "Kaba davranan, hayırdan mahrum kalır.", "kaynak": "Müslim, Birr, 74" },
  { "id": 312, "metin": "İnsanların en şerlisi, ikiyüzlü olanlardır. Onlara bir yüzle, bunlara başka bir yüzle giderler.", "kaynak": "Buhârî, Edeb, 52" },
  { "id": 313, "metin": "Haya (utanma), ancak hayır getirir.", "kaynak": "Buhârî, Edeb, 77" },
  { "id": 314, "metin": "Sizden biriniz ayakkabısını giyerken sağdan, çıkarırken soldan başlasın.", "kaynak": "Buhârî, Libâs, 38" },
  { "id": 315, "metin": "Sağ el, temizlik ve yemek içindir; sol el ise diğer işler içindir.", "kaynak": "Ebû Dâvûd, Tahâret, 18" },
  { "id": 316, "metin": "Biriniz su içtiği zaman kabın içine nefes vermesin.", "kaynak": "Buhârî, Vudû, 19" },
  { "id": 317, "metin": "Deve gibi bir nefeste içmeyin; iki veya üç nefeste için. İçerken Besmele çekin, bitirince Hamd edin.", "kaynak": "Tirmizî, Eşribe, 13" },
  { "id": 318, "metin": "Altın ve ipek, ümmetimin erkeklerine haram, kadınlarına helal kılınmıştır.", "kaynak": "Tirmizî, Libâs, 1" },
  { "id": 319, "metin": "Kim resim (canlı sureti) yaparsa, kıyamet günü Allah ona 'Yaptığına can ver' diye azap eder.", "kaynak": "Buhârî, Tâbir, 45" },
  { "id": 320, "metin": "Kim yatsı namazını cemaatle kılarsa, gecenin yarısını ibadetle geçirmiş gibidir.", "kaynak": "Müslim, Mesâcid, 260" },
  { "id": 321, "metin": "Kim sabah namazını da cemaatle kılarsa, bütün geceyi ibadetle geçirmiş gibi olur.", "kaynak": "Müslim, Mesâcid, 260" },
  { "id": 322, "metin": "Sizden biri mescide girdiği zaman iki rekat (Tahiyyetü'l-Mescid) namazı kılmadan oturmasın.", "kaynak": "Buhârî, Salât, 60" },
  { "id": 323, "metin": "Kıyamet günü müezzinler, insanların en uzun boylusu (en çok dikkat çekeni) olacaklardır.", "kaynak": "Müslim, Salât, 14" },
  { "id": 324, "metin": "Kim ezanı işitir de 'Allah'ım! Bu davetin sahibi...' duasını okursa, ona şefaatim vacip olur.", "kaynak": "Buhârî, Ezân, 8" },
  { "id": 325, "metin": "Ya hayır konuş ya da sus.", "kaynak": "Buhârî, Edeb, 85" },
  { "id": 326, "metin": "Bir adamın 'İnsanlar helak oldu' dediğini duyarsanız, bilin ki en çok helak olan kendisidir.", "kaynak": "Müslim, Birr, 139" },
  { "id": 327, "metin": "Kişi, arkadaşının dini (ahlakı) üzeredir.", "kaynak": "Tirmizî, Zühd, 45" },
  { "id": 328, "metin": "Müminler, tek bir adam gibidir; başı ağrısa bütün vücudu sızlar.", "kaynak": "Müslim, Birr, 67" },
  { "id": 329, "metin": "Siz yeryüzündekilere merhamet edin ki, gökyüzündekiler de size merhamet etsin.", "kaynak": "Tirmizî, Birr, 16" },
  { "id": 330, "metin": "Rızkı, yerin derinliklerinde (çalışarak) arayın.", "kaynak": "Taberânî (Hasen)" },
  { "id": 331, "metin": "Allah, kulunun yemek yedikten veya bir şey içtikten sonra kendisine hamdetmesinden hoşnut olur.", "kaynak": "Müslim, Zikir, 89" },
  { "id": 332, "metin": "Besmelesiz yenen yemeğin bereketi olmaz.", "kaynak": "İbn Mâce, Et'ime, 8" },
  { "id": 333, "metin": "Yemeğin bereketi, yemekten önce ve sonra elleri yıkamaktadır.", "kaynak": "Tirmizî, Et'ime, 39" },
  { "id": 334, "metin": "Biriniz davet edildiği yere gitsin; oruçlu ise dua etsin, değilse yesin.", "kaynak": "Müslim, Sıyâm, 159" },
  { "id": 335, "metin": "Misafirlik üç gündür. Bundan fazlası sadakadır.", "kaynak": "Buhârî, Edeb, 31" },
  { "id": 336, "metin": "Kim (din) kardeşine 'Ey Kafir!' derse, bu söz ikisinden birine döner.", "kaynak": "Buhârî, Edeb, 73" },
  { "id": 337, "metin": "Müslümanın kanı, malı ve ırzı diğer Müslümana haramdır.", "kaynak": "Müslim, Birr, 32" },
  { "id": 338, "metin": "Haset, ateşin odunu yediği gibi iyilikleri yer bitirir.", "kaynak": "İbn Mâce, Zühd, 22" },
  { "id": 339, "metin": "Allah, kibirli ve övünen kimseyi sevmez.", "kaynak": "Lokmân Suresi, 18 (Ayet destekli hadis)" },
  { "id": 340, "metin": "Kim tevazu gösterirse Allah onu yüceltir, kim kibirlenirse Allah onu alçaltır.", "kaynak": "İbn Mâce, Zühd, 16" },
  { "id": 341, "metin": "Kıyamet günü cehennemlikler; kaba, cimri ve kibirli olanlardır.", "kaynak": "Buhârî, Edeb, 61" },
  { "id": 342, "metin": "Kim bir yetimin başını Allah rızası için okşarsa, elinin değdiği her saç teli kadar sevap alır.", "kaynak": "Müsned, 5/250" },
  { "id": 343, "metin": "Dul ve yetimlerin ihtiyaçlarına koşan, Allah yolunda cihat eden gibidir.", "kaynak": "Buhârî, Edeb, 25" },
  { "id": 344, "metin": "Çocuklarınıza ikramda bulunun ve terbiyelerini güzel yapın.", "kaynak": "İbn Mâce, Edeb, 3" },
  { "id": 345, "metin": "Allah'ın rızası babanın rızasında, öfkesi de babanın öfkesindedir.", "kaynak": "Tirmizî, Birr, 3" },
  { "id": 346, "metin": "Cennetin kokusu beş yüz yıllık mesafeden duyulur; ancak ana-babasına asi olan kokusunu alamaz.", "kaynak": "Taberânî" },
  { "id": 347, "metin": "Büyüklerine saygı göstermeyen, küçüklerine merhamet etmeyen bizden değildir.", "kaynak": "Ebû Dâvûd, Edeb, 58" },
  { "id": 348, "metin": "Kim rızkının bol olmasını istiyorsa akrabasını ziyaret etsin.", "kaynak": "Buhârî, Büyû, 13" },
  { "id": 349, "metin": "Sadakanın en faziletlisi, içinde düşmanlık besleyen akrabaya verilendir.", "kaynak": "Müsned, 3/402" },
  { "id": 350, "metin": "Komşun, şerrinden emin olmadıkça iman etmiş olmazsın.", "kaynak": "Buhârî, Edeb, 29" },
  { "id": 351, "metin": "Cebrail bana komşuyu o kadar tavsiye etti ki, komşuyu komşuya mirasçı kılacak sandım.", "kaynak": "Buhârî, Edeb, 28" },
  { "id": 352, "metin": "Evinizi namaz kılarak ve Kuran okuyarak nurlandırın.", "kaynak": "Beyhakî" },
  { "id": 353, "metin": "Namaz kılanın önünden geçmektense, kırk yıl beklemek daha hayırlıdır.", "kaynak": "Buhârî, Salât, 101" },
  { "id": 354, "metin": "Allah, esneyeni sever, aksırana ise rahmet eder. Esneme şeytandandır.", "kaynak": "Buhârî, Edeb, 125" },
  { "id": 355, "metin": "Biriniz uykudan uyandığında burnunu üç defa yıkasın; çünkü şeytan genzinde geceler.", "kaynak": "Buhârî, Bedü'l-halk, 11" },
  { "id": 356, "metin": "Abdest üzerine abdest almak nur üstüne nurdur.", "kaynak": "Aclûnî" },
  { "id": 357, "metin": "Kim güzelce abdest alırsa, günahları tırnaklarının altına kadar vücudundan çıkar.", "kaynak": "Müslim, Tahâret, 33" },
  { "id": 358, "metin": "Müminler ölmezler, sadece bir evden diğer bir eve (dünyadan ahirete) taşınırlar.", "kaynak": "Deylemî" },
  { "id": 359, "metin": "Ölümü çokça hatırlayın; çünkü o, zevkleri bıçak gibi keser.", "kaynak": "Tirmizî, Zühd, 4" },
  { "id": 360, "metin": "Hasta ziyareti yapan kimse, dönünceye kadar cennet bahçesindedir.", "kaynak": "Müslim, Birr, 40" },
  { "id": 361, "metin": "Hastaya, 'Allah sana şifa versin' diye dua etmek sünnettir.", "kaynak": "Tirmizî, Tıb, 32" },
  { "id": 362, "metin": "Tedavi olun ey Allah'ın kulları! Allah her hastalığın şifasını yaratmıştır.", "kaynak": "Ebû Dâvûd, Tıb, 1" },
  { "id": 363, "metin": "Çörek otunda ölüm hariç her derde deva vardır.", "kaynak": "Buhârî, Tıb, 7" },
  { "id": 364, "metin": "Balda şifa vardır.", "kaynak": "Buhârî, Tıb, 3" },
  { "id": 365, "metin": "Sihir ve büyü yapan cennete giremez.", "kaynak": "Nesaî, Tahrîm, 19" },
  { "id": 366, "metin": "Müslümanın silahı duadır.", "kaynak": "Hâkim, Müstedrek" },
  { "id": 367, "metin": "Allah'tan istemeyene Allah gazap eder.", "kaynak": "Tirmizî, Deavât, 2" },
  { "id": 368, "metin": "Acele etmediğiniz sürece duanız kabul olunur.", "kaynak": "Buhârî, Deavât, 22" },
  { "id": 369, "metin": "Mazlumun bedduasından sakın, kafir bile olsa.", "kaynak": "Müsned" },
  { "id": 370, "metin": "Allah, ısrarla dua edenleri sever.", "kaynak": "Taberânî" },
  { "id": 371, "metin": "Gizli verilen sadaka, Rabbin gazabını söndürür.", "kaynak": "Taberânî" },
  { "id": 372, "metin": "Gülümsemek sadakadır.", "kaynak": "Tirmizî, Birr, 36" },
  { "id": 373, "metin": "Güzel ahlak, güneşin buzu erittiği gibi günahları eritir.", "kaynak": "Taberânî" },
  { "id": 374, "metin": "Kötü ahlak, sirkenin balı bozduğu gibi ameli bozar.", "kaynak": "Taberânî" },
  { "id": 375, "metin": "Doğruluk huzur, yalan ise şüphedir.", "kaynak": "Tirmizî, Kıyâmet, 60" },
  { "id": 376, "metin": "Yalan ile iman bir arada bulunmaz.", "kaynak": "Müsned" },
  { "id": 377, "metin": "Emanete riayeti olmayanın imanı yoktur.", "kaynak": "Müsned, 3/135" },
  { "id": 378, "metin": "Müslüman, elinden ve dilinden insanların emin olduğu kimsedir.", "kaynak": "Tirmizî, Îmân, 12" },
  { "id": 379, "metin": "Kim bir Müslümanın ayıbını araştırırsa, Allah da onun ayıbını araştırır.", "kaynak": "Ebû Dâvûd, Edeb, 35" },
  { "id": 380, "metin": "Zandan kaçının, çünkü zan sözlerin en yalanıdır.", "kaynak": "Buhârî, Vasâyâ, 8" },
  { "id": 381, "metin": "Su-i zan (kötü düşünce) etmeyin, casusluk yapmayın.", "kaynak": "Müslim, Birr, 28" },
  { "id": 382, "metin": "İnsanlara teşekkür etmeyen Allah'a şükretmez.", "kaynak": "Ebû Dâvûd, Edeb, 11" },
  { "id": 383, "metin": "Kanaat, tükenmez bir hazinedir.", "kaynak": "Beyhakî" },
  { "id": 384, "metin": "Dünya sevgisi bütün hataların başıdır.", "kaynak": "Beyhakî" },
  { "id": 385, "metin": "Zühd, dünyayı (kalben) terk etmektir.", "kaynak": "İbn Mâce, Zühd, 1" },
  { "id": 386, "metin": "Akıllı kimse, nefsine hakim olan ve ölüm sonrası için çalışandır.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 387, "metin": "Tövbe, günahı tamamen terk etmektir.", "kaynak": "Müsned" },
  { "id": 388, "metin": "Günahtan tam dönen, hiç günah işlememiş gibidir.", "kaynak": "İbn Mâce, Zühd, 30" },
  { "id": 389, "metin": "Allah, geceleyin günah işleyenin tövbe etmesi için gündüz elini açar.", "kaynak": "Müslim, Tövbe, 31" },
  { "id": 390, "metin": "Allah'ın rahmetinden ümidinizi kesmeyin.", "kaynak": "Zümer Suresi, 53 (Ayet destekli hadis)" },
  { "id": 391, "metin": "Allah'ın azabı çetindir.", "kaynak": "Buhârî, Edeb, 18" },
  { "id": 392, "metin": "Cehennem ateşi, dünya ateşinden altmış dokuz kat daha sıcaktır.", "kaynak": "Buhârî, Bedü'l-halk, 10" },
  { "id": 393, "metin": "Sırat köprüsü, kıldan ince kılıçtan keskindir.", "kaynak": "Müslim, Îmân, 329" },
  { "id": 394, "metin": "Kıyamet günü, boynuzsuz koyun boynuzlu koyundan hakkını alacaktır.", "kaynak": "Müslim, Birr, 60" },
  { "id": 395, "metin": "Müflis, kıyamet günü sevaplarıyla gelip, kul hakları yüzünden onları kaybedendir.", "kaynak": "Müslim, Birr, 59" },
  { "id": 396, "metin": "Allah, adil yöneticileri sever.", "kaynak": "Müslim, İmare, 18" },
  { "id": 397, "metin": "Yöneticileriniz sizin amellerinizin aynasıdır.", "kaynak": "Aclûnî" },
  { "id": 398, "metin": "İtaat, ancak hayırlı işlerdedir; Allah'a isyan konusunda kula itaat yoktur.", "kaynak": "Buhârî, Ahkâm, 43" },
  { "id": 399, "metin": "Her kim İslam'da güzel bir çığır açarsa, onun ve onunla amel edenlerin sevabı ona yazılır.", "kaynak": "Müslim, İlim, 15" },
  { "id": 400, "metin": "Amellerin sonuncusu (son nefes) önemlidir.", "kaynak": "Buhârî, Rikâk, 11" },
  { "id": 401, "metin": "Allah'a ve ahiret gününe iman eden, ya hayır söylesin ya da sussun.", "kaynak": "Buhârî, Edeb, 31" },
  { "id": 402, "metin": "Sizden biriniz, kendisi için sevip arzu ettiği şeyi din kardeşi için de sevip arzu etmedikçe gerçek mümin olamaz.", "kaynak": "Buhârî, Îmân, 7" },
  { "id": 403, "metin": "İman, sabır ve müsamahadır.", "kaynak": "İbn Hanbel, 4/385" },
  { "id": 404, "metin": "Müslümanın Müslüman üzerindeki hakkı altıdır: Karşılaşınca selam ver, davet ederse git, nasihat isterse et, aksırırsa dua et, hastalanırsa ziyaret et, ölürse cenazesine git.", "kaynak": "Müslim, Selâm, 5" },
  { "id": 405, "metin": "Allah sizin şekillerinize ve mallarınıza bakmaz, ancak kalplerinize ve amellerinize bakar.", "kaynak": "Müslim, Birr, 34" },
  { "id": 406, "metin": "Zulümden sakının! Çünkü zulüm, kıyamet gününde karanlıklar olacaktır.", "kaynak": "Müslim, Birr, 56" },
  { "id": 407, "metin": "Her iyilik bir sadakadır.", "kaynak": "Buhârî, Edeb, 33" },
  { "id": 408, "metin": "İnsanlara merhamet etmeyene Allah merhamet etmez.", "kaynak": "Müslim, Fedâil, 66" },
  { "id": 409, "metin": "Kolaylaştırınız, zorlaştırmayınız; müjdeleyiniz, nefret ettirmeyiniz.", "kaynak": "Buhârî, İlim, 11" },
  { "id": 410, "metin": "Haya imandandır.", "kaynak": "Buhârî, Îmân, 16" },
  { "id": 411, "metin": "Kıyamet gününde müminin mizanında güzel ahlaktan daha ağır basan bir şey yoktur.", "kaynak": "Tirmizî, Birr, 62" },
  { "id": 412, "metin": "Söz taşıyan (kovuculuk yapan) cennete giremez.", "kaynak": "Buhârî, Edeb, 50" },
  { "id": 413, "metin": "Akrabalık bağını koparan cennete giremez.", "kaynak": "Buhârî, Edeb, 11" },
  { "id": 414, "metin": "Komşusu açken tok yatan bizden değildir.", "kaynak": "İbn Ebi Şeybe, Musannef, 8/164" },
  { "id": 415, "metin": "Mümin, bir delikten iki defa ısırılmaz (aynı hatayı iki kez yapmaz).", "kaynak": "Buhârî, Edeb, 83" },
  { "id": 416, "metin": "İçki bütün kötülüklerin anahtarıdır.", "kaynak": "İbn Mâce, Eşribe, 1" },
  { "id": 417, "metin": "Rüşvet alan da veren de cehennemdedir.", "kaynak": "Taberânî, el-Mu'cemü'l-Evsat" },
  { "id": 418, "metin": "Faiz yiyen, yediren, yazan ve şahitlik edenler lanetlenmiştir.", "kaynak": "Müslim, Müsâkât, 106" },
  { "id": 419, "metin": "Kim haksız yere bir karış toprak gasp ederse, kıyamet günü o toprak yedi kat olarak boynuna dolanır.", "kaynak": "Buhârî, Mezâlim, 13" },
  { "id": 420, "metin": "Anne ve babasına iyilik edene ne mutlu! Allah onun ömrünü bereketlendirsin.", "kaynak": "Heysemî, Mecmeu'z-Zevâid, 8/137" },
  { "id": 421, "metin": "Cennet annelerin ayakları altındadır.", "kaynak": "Nesâî, Cihâd, 6" },
  { "id": 422, "metin": "Babanın rızası Allah'ın rızasında, babanın öfkesi Allah'ın öfkesindedir.", "kaynak": "Tirmizî, Birr, 3" },
  { "id": 423, "metin": "Sizin en hayırlınız, ailesine karşı en hayırlı olanınızdır.", "kaynak": "İbn Mâce, Nikâh, 50" },
  { "id": 424, "metin": "Kadınlar erkeklerin (tamamlayıcı) parçalarıdır.", "kaynak": "Ebû Dâvûd, Tahâret, 94" },
  { "id": 425, "metin": "Kişinin harcadığı en hayırlı para, ailesine harcadığı paradır.", "kaynak": "Müslim, Zekât, 38" },
  { "id": 426, "metin": "Hiçbir baba, çocuğuna güzel ahlaktan daha kıymetli bir miras bırakmamıştır.", "kaynak": "Tirmizî, Birr, 33" },
  { "id": 427, "metin": "Çocuklarınıza saygılı davranın, onlarla alay etmeyin, onlara hakaret etmeyin.", "kaynak": "İbn Mâce, Edeb, 3" },
  { "id": 428, "metin": "Münafığın alameti üçtür: Konuşunca yalan söyler, söz verince durmaz, emanete hıyanet eder.", "kaynak": "Buhârî, Îmân, 24" },
  { "id": 429, "metin": "Dört özellik kimde bulunursa o tam münafık olur: Yalan söylemek, sözünden dönmek, emanete hıyanet etmek, düşmanlıkta aşırı gitmek.", "kaynak": "Buhârî, Îmân, 24" },
  { "id": 430, "metin": "Kıyamet günü Allah katında en kötü insan, iki yüzlü olandır.", "kaynak": "Buhârî, Edeb, 52" },
  { "id": 431, "metin": "Bizi aldatan bizden değildir.", "kaynak": "Müslim, Îmân, 164" },
  { "id": 432, "metin": "Yalan, insanı kötülüğe, kötülük de cehenneme götürür.", "kaynak": "Buhârî, Edeb, 69" },
  { "id": 433, "metin": "Doğruluk iyiliğe, iyilik de cennete götürür.", "kaynak": "Buhârî, Edeb, 69" },
  { "id": 434, "metin": "Şüpheli şeyleri bırak, şüphe vermeyen şeylere bak.", "kaynak": "Buhârî, Büyû, 3" },
  { "id": 435, "metin": "Kim bir kötülük görürse onu eliyle, gücü yetmezse diliyle, ona da gücü yetmezse kalbiyle düzeltsin.", "kaynak": "Müslim, Îmân, 78" },
  { "id": 436, "metin": "İyiliğe anahtar, kötülüğe kilit olanlara müjdeler olsun.", "kaynak": "İbn Mâce, Mukaddime, 19" },
  { "id": 437, "metin": "Din nasihattir (samimiyettir).", "kaynak": "Müslim, Îmân, 95" },
  { "id": 438, "metin": "Ameller niyetlere göredir.", "kaynak": "Buhârî, Bedü'l-Vahy, 1" },
  { "id": 439, "metin": "Allah'ın en sevdiği amel, az da olsa devamlı olanıdır.", "kaynak": "Buhârî, Îmân, 32" },
  { "id": 440, "metin": "Acele şeytandandır, teenni (yavaş ve dikkatli davranmak) Allah'tandır.", "kaynak": "Tirmizî, Birr, 66" },
  { "id": 441, "metin": "Tevbe eden, hiç günah işlememiş gibidir.", "kaynak": "İbn Mâce, Zühd, 30" },
  { "id": 442, "metin": "İnsanoğlunun hepsi hatadıdır. Hata edenlerin en hayırlısı ise tevbe edenlerdir.", "kaynak": "Tirmizî, Kıyâmet, 49" },
  { "id": 443, "metin": "Allah, kulunun tevbesinden, (çölde) devesini kaybedip bulan kimseden daha çok sevinir.", "kaynak": "Buhârî, Deavât, 4" },
  { "id": 444, "metin": "Kim bir Müslümanın ayıbını örterse, Allah da kıyamet günü onun ayıbını örter.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 445, "metin": "Kim kardeşinin ihtiyacını görürse, Allah da onun ihtiyacını görür.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 446, "metin": "Müslüman, elinden ve dilinden Müslümanların emin olduğu kimsedir.", "kaynak": "Buhârî, Îmân, 4" },
  { "id": 447, "metin": "Gerçek zenginlik mal çokluğu değil, gönül zenginliğidir.", "kaynak": "Buhârî, Rikâk, 15" },
  { "id": 448, "metin": "Kanaat tükenmez bir hazinedir.", "kaynak": "Beyhakî, Zühd, 2/88" },
  { "id": 449, "metin": "Dünya sevgisi her hatanın başıdır.", "kaynak": "Beyhakî, Şuabü'l-iman, 7/338" },
  { "id": 450, "metin": "Akıllı kimse, nefsini hesaba çeken ve ölümden sonrası için çalışandır.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 451, "metin": "Dünyada bir garip veya yolcu gibi ol.", "kaynak": "Buhârî, Rikâk, 3" },
  { "id": 452, "metin": "Lezzetleri bıçak gibi kesen ölümü çokça hatırlayın.", "kaynak": "Tirmizî, Zühd, 4" },
  { "id": 453, "metin": "Ölüyü kabre kadar üç şey takip eder: Ailesi, malı ve ameli. İkisi döner, biri kalır: Ameli.", "kaynak": "Buhârî, Rikâk, 42" },
  { "id": 454, "metin": "Kabir, ya cennet bahçelerinden bir bahçe veya cehennem çukurlarından bir çukurdur.", "kaynak": "Tirmizî, Kıyâmet, 26" },
  { "id": 455, "metin": "Kim Allah'a kavuşmayı severse, Allah da ona kavuşmayı sever.", "kaynak": "Buhârî, Rikâk, 41" },
  { "id": 456, "metin": "Kuran okuyunuz. Çünkü o, kıyamet günü okuyanlarına şefaatçi olarak gelecektir.", "kaynak": "Müslim, Müsâfirîn, 252" },
  { "id": 457, "metin": "Sizin en hayırlınız, Kuran'ı öğrenen ve öğretendir.", "kaynak": "Buhârî, Fedâilü'l-Kur'ân, 21" },
  { "id": 458, "metin": "İçinde Kuran'dan bir şey bulunmayan kalp, harap olmuş ev gibidir.", "kaynak": "Tirmizî, Fedâilü'l-Kur'ân, 18" },
  { "id": 459, "metin": "Kim Kuran'dan bir harf okursa, ona bir sevap vardır. Her sevap on misliyle katlanır.", "kaynak": "Tirmizî, Fedâilü'l-Kur'ân, 16" },
  { "id": 460, "metin": "Dua ibadetin özüdür.", "kaynak": "Tirmizî, Deavât, 1" },
  { "id": 461, "metin": "Kabul edileceğine inanarak Allah'a dua ediniz.", "kaynak": "Tirmizî, Deavât, 65" },
  { "id": 462, "metin": "Allah, ısrarla dua edenleri sever.", "kaynak": "Beyhakî, Şuabü'l-iman, 2/1107" },
  { "id": 463, "metin": "Mazlumun bedduasından sakının. Çünkü onunla Allah arasında perde yoktur.", "kaynak": "Buhârî, Zekât, 63" },
  { "id": 464, "metin": "Üç dua reddedilmez: Babanın evladına duası, oruçlunun duası, yolcunun duası.", "kaynak": "Beyhakî, 3/345" },
  { "id": 465, "metin": "Allah'ı zikredenle zikretmeyenin misali, diri ile ölü gibidir.", "kaynak": "Buhârî, Deavât, 66" },
  { "id": 466, "metin": "Dilin, sürekli Allah'ı zikretmekle ıslak kalsın.", "kaynak": "Tirmizî, Deavât, 4" },
  { "id": 467, "metin": "İki kelime vardır ki, dile hafif, mizanda ağır ve Allah'a sevimlidir: Sübhanallahi ve bihamdihi, Sübhanallahil azim.", "kaynak": "Buhârî, Deavât, 65" },
  { "id": 468, "metin": "Cennetin anahtarı namazdır.", "kaynak": "Tirmizî, Tahâret, 1" },
  { "id": 469, "metin": "Namaz dinin direğidir.", "kaynak": "Tirmizî, Îmân, 8" },
  { "id": 470, "metin": "Kıyamet günü kulun ilk hesaba çekileceği şey namazdır.", "kaynak": "Tirmizî, Salât, 188" },
  { "id": 471, "metin": "Kulun Rabbine en yakın olduğu an secde anıdır.", "kaynak": "Müslim, Salât, 215" },
  { "id": 472, "metin": "Beş vakit namaz ve Cuma namazı, büyük günahlardan kaçınıldığı sürece aradaki günahlara kefarettir.", "kaynak": "Müslim, Tahâret, 16" },
  { "id": 473, "metin": "Cemaatle kılınan namaz, tek başına kılınan namazdan yirmi yedi derece daha faziletlidir.", "kaynak": "Buhârî, Ezân, 30" },
  { "id": 474, "metin": "Sabah namazının iki rekat sünneti, dünyadan ve içindeki her şeyden hayırlıdır.", "kaynak": "Müslim, Müsâfirîn, 96" },
  { "id": 475, "metin": "Oruç sabrın yarısıdır.", "kaynak": "İbn Mâce, Sıyâm, 44" },
  { "id": 476, "metin": "Oruç bir kalkandır.", "kaynak": "Buhârî, Savm, 2" },
  { "id": 477, "metin": "Kim inanarak ve sevabını Allah'tan bekleyerek Ramazan orucunu tutarsa geçmiş günahları bağışlanır.", "kaynak": "Buhârî, Savm, 6" },
  { "id": 478, "metin": "Sahur yemeği yiyin, zira sahurda bereket vardır.", "kaynak": "Buhârî, Savm, 20" },
  { "id": 479, "metin": "İftar anında oruçlunun reddedilmeyen bir duası vardır.", "kaynak": "İbn Mâce, Sıyâm, 48" },
  { "id": 480, "metin": "Veren el alan elden üstündür.", "kaynak": "Buhârî, Zekât, 18" },
  { "id": 481, "metin": "Sadaka malı eksiltmez.", "kaynak": "Müslim, Birr, 69" },
  { "id": 482, "metin": "Yarım hurma ile de olsa ateşten korunun.", "kaynak": "Buhârî, Edeb, 34" },
  { "id": 483, "metin": "Güzel söz sadakadır.", "kaynak": "Buhârî, Edeb, 34" },
  { "id": 484, "metin": "Her Müslüman üzerine sadaka vermek vaciptir.", "kaynak": "Buhârî, Zekât, 30" },
  { "id": 485, "metin": "En faziletli sadaka, Müslümanın ilim öğrenip başkasına öğretmesidir.", "kaynak": "İbn Mâce, Sünnet, 20" },
  { "id": 486, "metin": "Hac ve umre yapanlar Allah'ın misafirleridir.", "kaynak": "İbn Mâce, Menâsik, 5" },
  { "id": 487, "metin": "Mebrur (kabul olunmuş) haccın karşılığı ancak cennettir.", "kaynak": "Buhârî, Umre, 1" },
  { "id": 488, "metin": "Allah yolunda tozlanan ayaklara cehennem ateşi haramdır.", "kaynak": "Buhârî, Cihâd, 16" },
  { "id": 489, "metin": "Kim ilim öğrenmek için yola çıkarsa, Allah ona cennet yolunu kolaylaştırır.", "kaynak": "Müslim, Zikir, 39" },
  { "id": 490, "metin": "İlim, müminin yitiğidir; nerede bulursa alır.", "kaynak": "Tirmizî, İlim, 19" },
  { "id": 491, "metin": "Alimler peygamberlerin varisleridir.", "kaynak": "Ebû Dâvûd, İlim, 1" },
  { "id": 492, "metin": "Fayda vermeyen ilimden Allah'a sığınırım.", "kaynak": "Müslim, Zikir, 73" },
  { "id": 493, "metin": "İşçiye ücretini teri kurumadan veriniz.", "kaynak": "İbn Mâce, Ruhûn, 4" },
  { "id": 494, "metin": "Hiçbir kimse elinin emeğinden daha hayırlı bir lokma yememiştir.", "kaynak": "Buhârî, Büyû, 15" },
  { "id": 495, "metin": "Doğru sözlü ve güvenilir tüccar, peygamberler, sıddıklar ve şehitlerle beraberdir.", "kaynak": "Tirmizî, Büyû, 4" },
  { "id": 496, "metin": "Hastalık, Müslümanın günahlarına kefarettir.", "kaynak": "Buhârî, Merdâ, 1" },
  { "id": 497, "metin": "Hastayı ziyaret etmek, cennet bahçelerinde yürümek gibidir.", "kaynak": "Müslim, Birr, 40" },
  { "id": 498, "metin": "Şifayı veren ancak Allah'tır.", "kaynak": "Buhârî, Tıb, 1" },
  { "id": 499, "metin": "Nazar haktır (gerçektir).", "kaynak": "Müslim, Selâm, 41" },
  { "id": 500, "metin": "Allah güzeldir, güzelliği sever.", "kaynak": "Müslim, Îmân, 147" },
  { "id": 501, "metin": "Bereket yemeğin ortasına iner. Bu sebeple yemeği kenarlarından yiyin, ortasından yemeyin.", "kaynak": "Tirmizî, Et'ime, 12" },
  { "id": 502, "metin": "Biriniz yemek yerken ayakkabılarını çıkarsın. Çünkü bu, ayaklar için daha rahatlatıcıdır.", "kaynak": "Dârimî, Et'ime, 10" },
  { "id": 503, "metin": "Altın ve gümüş kaplardan su içmeyin, onlarda yemek yemeyin.", "kaynak": "Buhârî, Eşribe, 28" },
  { "id": 504, "metin": "Mide, hastalıkların evidir; perhiz ise tedavinin başıdır.", "kaynak": "Aclûnî, Keşfü'l-Hafâ" },
  { "id": 505, "metin": "Sizden biriniz sırtüstü yatıp bacak bacak üstüne atmasın.", "kaynak": "Müslim, Libâs, 74" },
  { "id": 506, "metin": "Yüzü koyun (karnının üzerine) yatmak, Allah'ın sevmediği bir yatış tarzıdır.", "kaynak": "Tirmizî, Edeb, 21" },
  { "id": 507, "metin": "İyi rüya Allah'tan, kötü rüya şeytandandır.", "kaynak": "Buhârî, Tâbir, 3" },
  { "id": 508, "metin": "Sizden biriniz hoşuna giden bir rüya görürse, onu sadece sevdiği kimselere anlatsın.", "kaynak": "Müslim, Rüyâ, 3" },
  { "id": 509, "metin": "Esnemek şeytandandır. Biriniz esneyeceği zaman gücü yettiği kadar onu tutmaya çalışsın.", "kaynak": "Müslim, Zühd, 57" },
  { "id": 510, "metin": "Beyaz elbise giyiniz; çünkü o daha temiz ve daha hoş görünür.", "kaynak": "Tirmizî, Edeb, 46" },
  { "id": 511, "metin": "Kim (kibirle) elbisesini yerde sürürse, Allah kıyamet günü onun yüzüne bakmaz.", "kaynak": "Buhârî, Libâs, 5" },
  { "id": 512, "metin": "Allah'ın verdiği nimetin eserinin, kulunun üzerinde görülmesi Allah'ın hoşuna gider.", "kaynak": "Tirmizî, Edeb, 54" },
  { "id": 513, "metin": "Aksırıp da 'Elhamdülillah' demeyen kimseye 'Yerhamükellah' demeyiniz.", "kaynak": "Müslim, Zühd, 54" },
  { "id": 514, "metin": "Bir meclisten kalkarken 'Sübhâneke Allâhümme ve bihamdik...' duasını okuyanın günahları bağışlanır.", "kaynak": "Tirmizî, Deavât, 39" },
  { "id": 515, "metin": "İzin istemek üç defadır. İzin verilirse girersin, verilmezse geri dönersin.", "kaynak": "Buhârî, İsti'zân, 13" },
  { "id": 516, "metin": "Birinin evinin içine (izinsiz) bakmak, o eve girmek demektir (haramdır).", "kaynak": "Tirmizî, İsti'zân, 1" },
  { "id": 517, "metin": "Meclislerde konuşulanlar emanettir.", "kaynak": "Ebû Dâvûd, Edeb, 32" },
  { "id": 518, "metin": "Kişi, (din) kardeşine, onun hoşuna gitmeyecek bir isim (lakap) takmasın.", "kaynak": "Tirmizî, Edeb, 60" },
  { "id": 519, "metin": "Mümin lanet edici değildir.", "kaynak": "Tirmizî, Birr, 48" },
  { "id": 520, "metin": "Ölülerinizi hayırla anın, kötülüklerini dile getirmekten sakının.", "kaynak": "Tirmizî, Cenâiz, 34" },
  { "id": 521, "metin": "Kabirlerin üzerine oturmayın ve onlara karşı namaz kılmayın.", "kaynak": "Müslim, Cenâiz, 97" },
  { "id": 522, "metin": "Cenaze namazı kıldığınız zaman, ölen kimseye samimiyetle dua edin.", "kaynak": "Ebû Dâvûd, Cenâiz, 54" },
  { "id": 523, "metin": "Ölü için feryat edip ağlayan bizden değildir.", "kaynak": "Buhârî, Cenâiz, 36" },
  { "id": 524, "metin": "Sabır, musibetin ilk geldiği andadır.", "kaynak": "Buhârî, Cenâiz, 32" },
  { "id": 525, "metin": "Müminin ruhu, ödeninceye kadar borcuna takılı kalır.", "kaynak": "Tirmizî, Cenâiz, 76" },
  { "id": 526, "metin": "İntihar eden kimse, cehennemde (intihar ettiği aletle) ebedi olarak azap görür.", "kaynak": "Buhârî, Tıb, 56" },
  { "id": 527, "metin": "Kim bir kahine gider ve onun söylediklerini tasdik ederse, Muhammed'e indirileni inkar etmiş olur.", "kaynak": "Ebû Dâvûd, Tıb, 21" },
  { "id": 528, "metin": "Uğursuzluk (inancı) şirktir.", "kaynak": "Ebû Dâvûd, Tıb, 24" },
  { "id": 529, "metin": "İslam'da (uğursuzluk sayıp) 'tatayyur' yoktur; en hayırlısı 'tefeül' (hayra yormak)tır.", "kaynak": "Buhârî, Tıb, 19" },
  { "id": 530, "metin": "Allah'tan başka kimsenin bilemeyeceği gaybın anahtarları beştir.", "kaynak": "Buhârî, İstiskâ, 29" },
  { "id": 531, "metin": "Kıyamet yaklaştığında zamanın bereketi azalır. Sene ay gibi, ay hafta gibi, hafta gün gibi olur.", "kaynak": "Tirmizî, Zühd, 24" },
  { "id": 532, "metin": "Fırat nehri altından bir dağ (hazine) ortaya çıkarmadıkça kıyamet kopmaz.", "kaynak": "Müslim, Fiten, 29" },
  { "id": 533, "metin": "Ahir zamanda türeyen, akılları kıt, yaşları küçük bir zümre Kuran okurlar ama gırtlaklarından aşağı inmez.", "kaynak": "Buhârî, Fezâilü'l-Kur'ân, 36" },
  { "id": 534, "metin": "Deccal'in iki gözü arasında 'Kafir' yazılıdır.", "kaynak": "Buhârî, Fiten, 26" },
  { "id": 535, "metin": "Kim Kehf Suresi'nin başından (veya sonundan) on ayet ezberlerse Deccal'den korunur.", "kaynak": "Müslim, Müsâfirîn, 257" },
  { "id": 536, "metin": "İstanbul elbette fetholunacaktır. Onu fetheden komutan ne güzel komutan, o ordu ne güzel ordudur.", "kaynak": "Müsned, 4/335" },
  { "id": 537, "metin": "İhlas Suresi, Kuran'ın üçte birine denktir.", "kaynak": "Buhârî, Fezâilü'l-Kur'ân, 13" },
  { "id": 538, "metin": "Mülk Suresi (Tebareke), kabir azabına engeldir.", "kaynak": "Tirmizî, Fezâilü'l-Kur'ân, 9" },
  { "id": 539, "metin": "Bakara Suresi'nin son iki ayetini (Amenerrasulü) gece okuyana, o gece için yeterlidir.", "kaynak": "Buhârî, Fezâilü'l-Kur'ân, 10" },
  { "id": 540, "metin": "Cuma günü Kehf Suresi'ni okuyan kimse için, iki Cuma arası nurla aydınlanır.", "kaynak": "Hâkim, Müstedrek, 2/399" },
  { "id": 541, "metin": "Sabah namazından sonra güneş doğuncaya kadar oturup Allah'ı zikretmek, bana köle azat etmekten daha sevimlidir.", "kaynak": "Ebû Dâvûd, İlim, 13" },
  { "id": 542, "metin": "İki nimet vardır ki, insanlardan çoğu bunda aldanmıştır: Sağlık ve boş vakit.", "kaynak": "Buhârî, Rikâk, 1" },
  { "id": 543, "metin": "İnsan yaşlansa da iki duygu onda hep genç kalır: Hırs ve tûl-i emel (uzun yaşama arzusu).", "kaynak": "Müslim, Zekât, 115" },
  { "id": 544, "metin": "Ademoğlunun iki vadi dolusu malı olsa, üçüncüsünü ister. Onun gözünü ancak toprak doyurur.", "kaynak": "Buhârî, Rikâk, 10" },
  { "id": 545, "metin": "Kuran'ı seslerinizle güzelleştirin.", "kaynak": "Ebû Dâvûd, Vitr, 20" },
  { "id": 546, "metin": "Kuran'ı hüzünle okuyun, çünkü o hüzünle inmiştir.", "kaynak": "Taberânî" },
  { "id": 547, "metin": "Allah şu Kuran ile bazı kavimleri yükseltir, bazılarını da alçaltır.", "kaynak": "Müslim, Müsâfirîn, 269" },
  { "id": 548, "metin": "Sizin en hayırlınız, borcunu en güzel ödeyendir.", "kaynak": "Buhârî, İstikrâz, 4" },
  { "id": 549, "metin": "Borçlu ölenin (kul hakkı olduğu için) cenaze namazını kıldırmam (buyururdu).", "kaynak": "Buhârî, Havâlât, 3" },
  { "id": 550, "metin": "Allah, satarken, alırken ve alacağını isterken kolaylık gösteren kimseyi sever.", "kaynak": "Buhârî, Büyû, 16" },
  { "id": 551, "metin": "Yalan yere yemin ederek malını satan kimseye, kıyamet günü Allah merhamet nazarıyla bakmaz.", "kaynak": "Müslim, Îmân, 171" },
  { "id": 552, "metin": "Alışveriş yapan iki kişi, birbirlerinden ayrılmadıkça (caymakta) muhayyerdirler.", "kaynak": "Buhârî, Büyû, 19" },
  { "id": 553, "metin": "Helal belli, haram da bellidir. İkisi arasında şüpheli şeyler vardır.", "kaynak": "Buhârî, Îmân, 39" },
  { "id": 554, "metin": "Bir kadınla bir erkek baş başa kalırsa, üçüncüleri şeytandır.", "kaynak": "Tirmizî, Radâ, 16" },
  { "id": 555, "metin": "Nikahın en hayırlısı, en kolay olanıdır.", "kaynak": "Ebû Dâvûd, Nikâh, 31" },
  { "id": 556, "metin": "Dul kadın kendisiyle ilgili karar vermede velisinden daha hak sahibidir.", "kaynak": "Müslim, Nikâh, 66" },
  { "id": 557, "metin": "Allah'a ve ahiret gününe iman eden kimse, yanında mahremi bulunmayan bir kadınla yalnız kalmasın.", "kaynak": "Müsned, 1/18" },
  { "id": 558, "metin": "Sizden kim evlenmeye güç yetirirse evlensin; çünkü evlilik gözü haramdan sakındırır.", "kaynak": "Buhârî, Savm, 10" },
  { "id": 559, "metin": "Dünya bir geçimliktir. Dünyanın en hayırlı varlığı saliha kadındır.", "kaynak": "Müslim, Radâ, 64" },
  { "id": 560, "metin": "Kadın, dört şeyi için nikahlanır: Malı, soyu, güzelliği ve dini. Sen dindar olanı seç.", "kaynak": "Buhârî, Nikâh, 15" },
  { "id": 561, "metin": "Anne-babasına hizmet eden, ömrünün bereketini görür.", "kaynak": "Müsned" },
  { "id": 562, "metin": "Cennetin orta kapısı, anne-babadır.", "kaynak": "Tirmizî, Birr, 3" },
  { "id": 563, "metin": "Allah'ın laneti, anne ve babasına sövenin üzerine olsun.", "kaynak": "Müslim, Edâhî, 43" },
  { "id": 564, "metin": "Kişinin, anne-babası hayatta iken cenneti kazanamaması ne büyük kayıptır!", "kaynak": "Tirmizî, Deavât, 100" },
  { "id": 565, "metin": "Zamanın boşa geçirilmesi, ölümden daha ağırdır.", "kaynak": "İbn Kayyim (Hikmetli söz olarak geçer, hadis manası taşır)" },
  { "id": 566, "metin": "Amelsiz ilim, meyvesiz ağaç gibidir.", "kaynak": "Aclûnî" },
  { "id": 567, "metin": "İlim, müminin yitiğidir.", "kaynak": "Tirmizî, İlim, 19" },
  { "id": 568, "metin": "Allah, ilmi insanlardan söküp almaz; alimlerin ölümüyle ilmi alır.", "kaynak": "Buhârî, İlim, 34" },
  { "id": 569, "metin": "Utanmadıktan sonra dilediğini yap!", "kaynak": "Buhârî, Enbiyâ, 54" },
  { "id": 570, "metin": "Zina eden, zina ettiği sırada (tam) mümin olarak zina etmez.", "kaynak": "Buhârî, Mezâlim, 30" },
  { "id": 571, "metin": "Gözlerin zinası bakmaktır, kulakların zinası dinlemektir.", "kaynak": "Müslim, Kader, 20" },
  { "id": 572, "metin": "Allah, yaşlı olduğu halde zina eden kimseye kıyamet günü bakmaz.", "kaynak": "Müslim, Îmân, 172" },
  { "id": 573, "metin": "Zaman gelecek, kişi malını helalden mi haramdan mı kazandığına aldırmayacak.", "kaynak": "Buhârî, Büyû, 7" },
  { "id": 574, "metin": "Helal rızık peşinde koşmak, her Müslümana farzdır.", "kaynak": "Taberânî" },
  { "id": 575, "metin": "Allah temizdir, ancak temiz olanı kabul eder.", "kaynak": "Müslim, Zekât, 65" },
  { "id": 576, "metin": "Ey insanlar! Allah'tan korkun ve rızkınızı güzel yollardan arayın.", "kaynak": "İbn Mâce, Ticâret, 2" },
  { "id": 577, "metin": "Şüphesiz rızık, eceli aradığı gibi kulun peşinden gider.", "kaynak": "Taberânî" },
  { "id": 578, "metin": "Sadaka vermek, malı eksiltmez.", "kaynak": "Müslim, Birr, 69" },
  { "id": 579, "metin": "Cömert, Allah'a yakındır, insanlara yakındır, cennete yakındır.", "kaynak": "Tirmizî, Birr, 40" },
  { "id": 580, "metin": "Cimri, Allah'tan uzaktır, insanlardan uzaktır, cehenneme yakındır.", "kaynak": "Tirmizî, Birr, 40" },
  { "id": 581, "metin": "Allah katında arkadaşların en hayırlısı, arkadaşına en iyi davranandır.", "kaynak": "Tirmizî, Birr, 28" },
  { "id": 582, "metin": "Salih bir arkadaş, misk taşıyan kimse gibidir.", "kaynak": "Buhârî, Zebâih, 31" },
  { "id": 583, "metin": "Kötü arkadaş, körük çeken kimse gibidir (ya üzerini yakar ya dumanı siner).", "kaynak": "Buhârî, Zebâih, 31" },
  { "id": 584, "metin": "Kişi dostunun dini üzeredir.", "kaynak": "Tirmizî, Zühd, 45" },
  { "id": 585, "metin": "Yalnızlık, kötü arkadaştan hayırlıdır; iyi arkadaş da yalnızlıktan hayırlıdır.", "kaynak": "Hâkim, Müstedrek" },
  { "id": 586, "metin": "Birbirinize hediye verin, birbirinizi sevin.", "kaynak": "Muvatta, Hüsnü'l-Hulk, 16" },
  { "id": 587, "metin": "Allah yolunda sevmek ve Allah yolunda buğzetmek imandandır.", "kaynak": "Ebû Dâvûd, Sünnet, 15" },
  { "id": 588, "metin": "Müslüman, Müslümanın aynasıdır.", "kaynak": "Ebû Dâvûd, Edeb, 49" },
  { "id": 589, "metin": "Din kardeşinle tartışmaya girme, onunla alay etme.", "kaynak": "Tirmizî, Birr, 58" },
  { "id": 590, "metin": "Kim tevazu gösterirse Allah onu yükseltir.", "kaynak": "Müslim, Birr, 69" },
  { "id": 591, "metin": "Allah'ım! Beni şükreden bir kul eyle.", "kaynak": "Ebû Dâvûd, Vitr, 25" },
  { "id": 592, "metin": "Hamd, şükrün başıdır. Allah'a hamdetmeyen O'na şükretmemiş olur.", "kaynak": "Deylemî" },
  { "id": 593, "metin": "İmana gelip de yaptığı hayırlara şükreden kimse kurtuluşa ermiştir.", "kaynak": "Müslim, Zekât, 125" },
  { "id": 594, "metin": "Sizden aşağıda olanlara bakın, yukarıda olanlara bakmayın. Bu, şükretmeniz için daha uygundur.", "kaynak": "Müslim, Zühd, 9" },
  { "id": 595, "metin": "Az malı olup da şükreden, çok malı olup da şükretmeyenden hayırlıdır.", "kaynak": "Aclûnî" },
  { "id": 596, "metin": "Musibete uğrayanı görünce 'Beni bundan koruyan Allah'a hamdolsun' diyen beladan korunur.", "kaynak": "Tirmizî, Deavât, 38" },
  { "id": 597, "metin": "Allah'ın kullarına en sevgili olanı, ahlakı en güzel olandır.", "kaynak": "Taberânî" },
  { "id": 598, "metin": "İman bakımından müminlerin en mükemmeli, ahlakça en güzel olanıdır.", "kaynak": "Tirmizî, Radâ, 11" },
  { "id": 599, "metin": "Ben ancak güzel ahlakı tamamlamak için gönderildim.", "kaynak": "Muvatta, Hüsnü'l-Hulk, 8" },
  { "id": 600, "metin": "Allah'ım! Yaratılışımı güzel yaptığın gibi ahlakımı da güzelleştir.", "kaynak": "Müsned, 1/403" },
  { "id": 601, "metin": "Ey kalpleri halden hale çeviren Allah'ım, kalbimi dinin üzere sabit kıl.", "kaynak": "Tirmizî, Deavât, 89" },
  { "id": 602, "metin": "Güçlü mümin, (Allah katında) zayıf müminden daha hayırlı ve daha sevimlidir.", "kaynak": "Müslim, Kader, 34" },
  { "id": 603, "metin": "Ahirete göre dünya, sizden birinizin parmağını denize daldırmasına benzer; o parmak ne kadar su ile dönerse dünya odur.", "kaynak": "Müslim, Cennet, 55" },
  { "id": 604, "metin": "Fıtrat beştir: Sünnet olmak, kasıkları tıraş etmek, tırnakları kesmek, koltuk altını temizlemek, bıyıkları kısaltmak.", "kaynak": "Buhârî, Libâs, 63" },
  { "id": 605, "metin": "Gece namazına devam edin; çünkü o, sizden önceki salihlerin adetidir.", "kaynak": "Tirmizî, Deavât, 101" },
  { "id": 606, "metin": "Allah, geceleyin namaz kılan ve eşini de uyandıran, uyanmazsa yüzüne su serpen erkeğe rahmet etsin.", "kaynak": "Ebû Dâvûd, Tatavvu, 18" },
  { "id": 607, "metin": "Kuşluk namazı, (Allah'a dönen) evvabların namazıdır.", "kaynak": "Müslim, Müsâfirîn, 143" },
  { "id": 608, "metin": "Biriniz bir işe niyetlendiği zaman iki rekat (İstihare) namazı kılsın.", "kaynak": "Buhârî, Teheccüd, 25" },
  { "id": 609, "metin": "Cemaate gelmeyenler evlerini yakasım geliyor.", "kaynak": "Buhârî, Ezân, 29" },
  { "id": 610, "metin": "Müezzini işittiğinizde, haydin namaza, haydin kurtuluşa dediği vakit, 'La havle ve la kuvvete illa billah' deyin.", "kaynak": "Buhârî, Ezân, 7" },
  { "id": 611, "metin": "İmam, kendisine uyulmak için vardır; o tekbir alınca siz de alın, o rükuya gidince siz de gidin.", "kaynak": "Buhârî, Salât, 18" },
  { "id": 612, "metin": "Kim yatsı namazını cemaatle kılarsa, sanki gecenin yarısını ihya etmiştir.", "kaynak": "Müslim, Mesâcid, 260" },
  { "id": 613, "metin": "Namazda sağa sola bakmaktan sakın; çünkü o, şeytanın kulun namazından çaldığı bir hırsızlıktır.", "kaynak": "Buhârî, Ezân, 93" },
  { "id": 614, "metin": "Secde ettiğinizde dengeli olun, kollarınızı köpeklerin yaydığı gibi yere yaymayın.", "kaynak": "Buhârî, Ezân, 141" },
  { "id": 615, "metin": "Namazın sonunda selam vermek, namazdan çıkmaktır.", "kaynak": "Ebû Dâvûd, Salât, 73" },
  { "id": 616, "metin": "Allah, temizlik yapmadan kılınan namazı kabul etmez.", "kaynak": "Müslim, Tahâret, 2" },
  { "id": 617, "metin": "Su bulamadığınız zaman temiz toprakla teyemmüm edin.", "kaynak": "Nisa Suresi, 43 (Ayet destekli hadis)" },
  { "id": 618, "metin": "Müslümanlar cuma günü camiye erkenden gitmekte yarışsalardı, bunun ne kadar faziletli olduğunu bilirlerdi.", "kaynak": "Buhârî, Ezân, 9" },
  { "id": 619, "metin": "Hutbe okunurken arkadaşına 'Sus' dersen, cuma sevabını zedelemiş olursun.", "kaynak": "Buhârî, Cuma, 36" },
  { "id": 620, "metin": "Arefe günü tutulan oruç, geçmiş ve gelecek birer yıllık günahlara kefaret olur.", "kaynak": "Müslim, Sıyâm, 196" },
  { "id": 621, "metin": "Aşure günü oruç tutun; zira o gün Allah'ın Musa'yı Firavun'dan kurtardığı gündür.", "kaynak": "Buhârî, Savm, 69" },
  { "id": 622, "metin": "Ramazan'dan sonra en faziletli oruç, Allah'ın ayı olan Muharrem ayında tutulan oruçtur.", "kaynak": "Müslim, Sıyâm, 202" },
  { "id": 623, "metin": "Kim Ramazan orucunu tutar ve ona Şevval ayından altı gün eklerse, bütün yılı oruçlu geçirmiş gibi olur.", "kaynak": "Müslim, Sıyâm, 204" },
  { "id": 624, "metin": "Sadaka vermek malı bereketlendirir.", "kaynak": "Müslim, Birr, 69" },
  { "id": 625, "metin": "Sizden biri, hurmanın yarısı ile de olsa sadaka vererek ateşten korunsun.", "kaynak": "Buhârî, Zekât, 10" },
  { "id": 626, "metin": "Hangi Müslüman, bir Müslümana elbise giydirirse, Allah da ona cennet elbiselerinden giydirir.", "kaynak": "Tirmizî, Kıyâmet, 41" },
  { "id": 627, "metin": "Yoksula verilen sadaka bir sadakadır; akrabaya verilen ise hem sadaka hem de sıla-i rahimdir.", "kaynak": "Tirmizî, Zekât, 26" },
  { "id": 628, "metin": "İnsan ölünce üç şey dışında ameli kesilir: Sadaka-i cariye, faydalanılan ilim, dua eden hayırlı evlat.", "kaynak": "Müslim, Vasiyyet, 14" },
  { "id": 629, "metin": "Umre, diğer umreye kadar aradaki günahlara kefarettir.", "kaynak": "Buhârî, Umre, 1" },
  { "id": 630, "metin": "Hacerü'l-Esved cennettendir.", "kaynak": "Tirmizî, Hac, 49" },
  { "id": 631, "metin": "Allah'ın evi (Kabe) çevresinde tavaf etmek namaz gibidir; ancak onda konuşmak serbesttir.", "kaynak": "Tirmizî, Hac, 112" },
  { "id": 632, "metin": "Kuran'ı ezberleyen kimse, vahiy getiren şerefli meleklerle beraberdir.", "kaynak": "Buhârî, Tevhîd, 52" },
  { "id": 633, "metin": "Kuran'ı zorlanarak da olsa okumaya çalışana iki sevap vardır.", "kaynak": "Müslim, Müsâfirîn, 244" },
  { "id": 634, "metin": "Kuran okunan yere melekler iner, rahmet kaplar ve huzur (sekine) iner.", "kaynak": "Müslim, Zikir, 38" },
  { "id": 635, "metin": "Kim Yasin Suresi'ni Allah rızası için okursa, geçmiş günahları bağışlanır.", "kaynak": "Beyhakî, Şuabü'l-İmân" },
  { "id": 636, "metin": "Dua eden, Rabbi ile fısıldaşır.", "kaynak": "Buhârî, Mevâkît, 8" },
  { "id": 637, "metin": "Allah'ım! Senden hidayet, takva, iffet ve gönül zenginliği isterim.", "kaynak": "Müslim, Zikir, 72" },
  { "id": 638, "metin": "Ey Rabbimiz! Bize dünyada da iyilik ver, ahirette de iyilik ver ve bizi ateş azabından koru.", "kaynak": "Buhârî, Deavât, 55" },
  { "id": 639, "metin": "Sizden biri dua ederken 'Allah'ım dilersen beni affet' demesin; kesin bir dille istesin.", "kaynak": "Buhârî, Deavât, 21" },
  { "id": 640, "metin": "Sevilmeyen bir şeyle karşılaşınca 'Kaderallahü ve ma şâe feal' (Allah'ın takdiri, O dilediğini yaptı) deyin.", "kaynak": "Müslim, Kader, 34" },
  { "id": 641, "metin": "Her kim 'Subhanallahi ve bihamdihi' derse, cennette onun için bir hurma ağacı dikilir.", "kaynak": "Tirmizî, Deavât, 60" },
  { "id": 642, "metin": "Kelime-i Tevhid'i (La ilahe illallah) çokça söyleyerek imanınızı tazeleyin.", "kaynak": "Müsned, 2/359" },
  { "id": 643, "metin": "Peygamberlere salavat getirmek, duaların kabulüne vesiledir.", "kaynak": "Tirmizî, Vitr, 21" },
  { "id": 644, "metin": "Cuma günü bana çokça salavat getirin; çünkü salavatınız bana arz olunur.", "kaynak": "Ebû Dâvûd, Salât, 201" },
  { "id": 645, "metin": "Müslüman, Müslümanın (din) kardeşidir. Ona zulmetmez, onu yardımsız bırakmaz.", "kaynak": "Buhârî, Mezâlim, 3" },
  { "id": 646, "metin": "Din kardeşin zalim de olsa, mazlum da olsa ona yardım et. (Zalimse, zulmüne engel ol).", "kaynak": "Buhârî, İkrâh, 7" },
  { "id": 647, "metin": "Gıybet eden ile dinleyen günahta ortaktır.", "kaynak": "Taberânî" },
  { "id": 648, "metin": "Nemime (laf taşıma) kabir azabının sebeplerindendir.", "kaynak": "Buhârî, Vudû, 55" },
  { "id": 649, "metin": "Zandan (kötü tahminden) sakının, çünkü zan sözün en yalanıdır.", "kaynak": "Buhârî, Vasâyâ, 8" },
  { "id": 650, "metin": "Birbirinize haset etmeyin, birbirinize küsmeyin, birbirinize sırt çevirmeyin.", "kaynak": "Müslim, Birr, 23" },
  { "id": 651, "metin": "Ey Allah'ın kulları! Kardeş olun.", "kaynak": "Buhârî, Edeb, 57" },
  { "id": 652, "metin": "Kibir, gerçeği reddetmek ve insanları hakir görmektir.", "kaynak": "Müslim, Îmân, 147" },
  { "id": 653, "metin": "Cehennemlikleri size haber vereyim mi? Kaba, cimri ve kibirli olan herkes.", "kaynak": "Buhârî, Edeb, 61" },
  { "id": 654, "metin": "Tevazu sahibi olanı Allah yüceltir.", "kaynak": "Müslim, Birr, 69" },
  { "id": 655, "metin": "İki kişi, aralarına üçüncü birini almadan fısıldaşmasınlar; bu onu üzer.", "kaynak": "Buhârî, İsti'zân, 47" },
  { "id": 656, "metin": "Meclislerde, size yer açıldığında siz de yer açın ki, Allah da size genişlik versin.", "kaynak": "Mücâdele Suresi, 11 (Ayet destekli hadis)" },
  { "id": 657, "metin": "Bir eve girdiğinizde ev halkına selam verin.", "kaynak": "Nûr Suresi, 61 (Ayet destekli hadis)" },
  { "id": 658, "metin": "Selam, kelamdan (konuşmadan) öncedir.", "kaynak": "Tirmizî, İsti'zân, 11" },
  { "id": 659, "metin": "Küçük büyüğe, yürüyen oturana, az olan çok olana selam verir.", "kaynak": "Buhârî, İsti'zân, 4" },
  { "id": 660, "metin": "Sizden biri hapşırırsa 'Elhamdülillah' desin. Kardeşi de ona 'Yerhamükellah' desin.", "kaynak": "Buhârî, Edeb, 126" },
  { "id": 661, "metin": "Misafirine ikram etmeyen bizden değildir.", "kaynak": "Müsned" },
  { "id": 662, "metin": "Misafirin duası makbuldür.", "kaynak": "Ebû Dâvûd, Vitr, 29" },
  { "id": 663, "metin": "Komşuna iyilik yap ki (gerçek) mümin olasın.", "kaynak": "Tirmizî, Zühd, 2" },
  { "id": 664, "metin": "Evinizi satın almadan önce komşunuzu araştırın.", "kaynak": "Taberânî" },
  { "id": 665, "metin": "Anne ve babasına asi olan cennete giremez.", "kaynak": "Nesâî, Zekât, 69" },
  { "id": 666, "metin": "Babanın dostunu ziyaret etmek, en büyük iyiliktir.", "kaynak": "Müslim, Birr, 11" },
  { "id": 667, "metin": "Akrabayı ziyaret, malı artırır, ömrü uzatır.", "kaynak": "Tirmizî, Birr, 49" },
  { "id": 668, "metin": "Çocuklarınıza yüzmeyi ve ok atmayı öğretin.", "kaynak": "Beyhakî" },
  { "id": 669, "metin": "Çocuğun babası üzerindeki hakkı, ona güzel bir isim koyması ve güzel terbiye vermesidir.", "kaynak": "Beyhakî" },
  { "id": 670, "metin": "Kadınlara hayırla muamele edin; çünkü onlar size Allah'ın emanetidir.", "kaynak": "Müslim, Radâ, 61" },
  { "id": 671, "metin": "Sizin en hayırlınız, hanımlarına karşı en iyi davrananızdır.", "kaynak": "Tirmizî, Radâ, 11" },
  { "id": 672, "metin": "Erkek, hanımına, hanım da erkeğine sevgiyle baktıklarında, Allah da onlara rahmetle bakar.", "kaynak": "Suyûtî" },
  { "id": 673, "metin": "Boşanma, Allah'ın en sevmediği helaldir.", "kaynak": "Ebû Dâvûd, Talâk, 3" },
  { "id": 674, "metin": "Helal kazanmak, cihattır.", "kaynak": "Deylemî" },
  { "id": 675, "metin": "Kazancın en temiz olanı, kişinin el emeğidir.", "kaynak": "Müsned, 2/334" },
  { "id": 676, "metin": "Allah, sanatkar (işini iyi yapan) mümin kulu sever.", "kaynak": "Taberânî" },
  { "id": 677, "metin": "Aldatan bizden değildir.", "kaynak": "Müslim, Îmân, 164" },
  { "id": 678, "metin": "Yalan yere yemin etmek, evin bereketini giderir.", "kaynak": "Buhârî, Edeb, 69" },
  { "id": 679, "metin": "Pazarlığa kızıştırmak (almayacağı halde fiyat artırmak) haramdır.", "kaynak": "Buhârî, Büyû, 58" },
  { "id": 680, "metin": "Borcunu ödeme niyetiyle alanın borcunu ödemesine Allah yardım eder.", "kaynak": "Buhârî, İstikrâz, 2" },
  { "id": 681, "metin": "Zengin olup da borcunu geciktirmek zulümdür.", "kaynak": "Buhârî, Havâlât, 1" },
  { "id": 682, "metin": "Faiz yiyen, (kabirden) şeytan çarpmış gibi kalkar.", "kaynak": "Bakara Suresi, 275 (Ayet destekli hadis)" },
  { "id": 683, "metin": "Haramdan sadaka olmaz.", "kaynak": "Müslim, Tahâret, 1" },
  { "id": 684, "metin": "Ölümü çokça anın; çünkü o, günahları temizler ve dünyadan soğutur.", "kaynak": "İbn Mâce, Zühd, 31" },
  { "id": 685, "metin": "Akıllı odur ki, nefsini hesaba çeker ve ölümden sonrası için hazırlık yapar.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 686, "metin": "Kabir, ahiret konaklarının ilkidir. Oradan kurtulan için sonrası daha kolaydır.", "kaynak": "Tirmizî, Zühd, 5" },
  { "id": 687, "metin": "Müminin ölümü, alnının terlemesiyle (hafif bir şekilde) olur.", "kaynak": "Tirmizî, Cenâiz, 10" },
  { "id": 688, "metin": "Ölünün arkasından yüksek sesle ağlamak ona azap verir.", "kaynak": "Buhârî, Cenâiz, 32" },
  { "id": 689, "metin": "Cenazeyi hızlı götürün. Eğer iyi biriyse onu hayra kavuşturursunuz.", "kaynak": "Buhârî, Cenâiz, 52" },
  { "id": 690, "metin": "Kıyamet gününde kul, ömrünü nerede tükettiğinden sorulacaktır.", "kaynak": "Tirmizî, Kıyâmet, 1" },
  { "id": 691, "metin": "Hesaba çekilmeden önce kendinizi hesaba çekin.", "kaynak": "Tirmizî, Kıyâmet, 25" },
  { "id": 692, "metin": "Sırat köprüsü üzerinde müminlerin nuru önlerini aydınlatır.", "kaynak": "Tahrîm Suresi, 8 (Ayet destekli hadis)" },
  { "id": 693, "metin": "Cehennem ateşi, (dünyadaki) ateşinizden yetmiş kat daha şiddetlidir.", "kaynak": "Müslim, Cennet, 30" },
  { "id": 694, "metin": "Cennette hiçbir gözün görmediği, hiçbir kulağın işitmediği nimetler vardır.", "kaynak": "Buhârî, Bedü'l-halk, 8" },
  { "id": 695, "metin": "Cennetliklerin en düşük derecesi, dünya ve içindekilerin on katı kadardır.", "kaynak": "Müslim, Îmân, 308" },
  { "id": 696, "metin": "Allah cennet ehline 'Razı oldunuz mu?' diye sorar, onlar da 'Nasıl razı olmayalım!' derler.", "kaynak": "Buhârî, Rikâk, 51" },
  { "id": 697, "metin": "Müminler cennette Rablerini dolunayı gördükleri gibi net göreceklerdir.", "kaynak": "Buhârî, Mevâkît, 16" },
  { "id": 698, "metin": "Sabır, cennet hazinelerinden bir hazinedir.", "kaynak": "Aclûnî" },
  { "id": 699, "metin": "Hayra vesile olan, hayrı yapan gibidir.", "kaynak": "Tirmizî, İlim, 14" },
  { "id": 700, "metin": "Allah'ım! Senden cenneti isterim, cehennemden sana sığınırım.", "kaynak": "Ebû Dâvûd, Salât, 179" }

]
